infix using "C:\COUNTRIES\NI81\NIHR81FL.dct"

label variable hhid     "Case Identification"
label variable hv000    "Country code and phase"
label variable hv001    "Cluster number"
label variable hv002    "Household number"
label variable hv003    "Respondent's line number (answering Household questionnaire)"
label variable hv004    "Ultimate area unit"
label variable hv005    "Household sample weight (6 decimals)"
label variable hv006    "Month of interview"
label variable hv007    "Year of interview"
label variable hv008    "Date of interview (CMC)"
label variable hv008a   "Date of interview Century Day Code (CDC)"
label variable hv009    "Number of household members"
label variable hv010    "Number of eligible women in household"
label variable hv011    "NA - Number of eligible men in household"
label variable hv012    "Number of de jure members"
label variable hv013    "Number of de facto members"
label variable hv014    "Number of children 5 and under (de jure)"
label variable hv015    "Result of household interview"
label variable hv016    "Day of interview"
label variable hv017    "Number of visits"
label variable hv018    "Interviewer identification"
label variable hv019    "NA - Keyer identification"
label variable hv020    "Ever-married sample"
label variable hv021    "Primary sampling unit"
label variable hv022    "Sample strata for sampling errors"
label variable hv023    "Stratification used in sample design"
label variable hv024    "Region"
label variable hv025    "Type of place of residence"
label variable hv026    "NA - Place of residence"
label variable hv027    "Household selected for male interview"
label variable hv028    "Household weight for male subsample (6 decimals)"
label variable hv030    "Field supervisor"
label variable hv031    "NA - Field editor"
label variable hv032    "NA - Office editor"
label variable hv035    "Number of eligible children for anemia and malaria"
label variable hv040    "Cluster altitude in meters"
label variable hv041    "NA - Total adults measured"
label variable hv042    "Household selected for hemoglobin"
label variable hv045a   "Language of questionnaire"
label variable hv045b   "Language of interview"
label variable hv045c   "Native language of respondent"
label variable hv046    "Translator used"
label variable hv801    "Time interview started (hhmm - 24 hour clock)"
label variable hv802    "Time interview ended (hhmm - 24 hour clock)"
label variable hv803    "Length of interview in minutes"
label variable hv804    "Number of visits for biomarker"
label variable hv807d   "Day of biomarker visit"
label variable hv807m   "Month of biomarker visit"
label variable hv807y   "Year of biomarker visit"
label variable hv807c   "Date of biomarker (CMC)"
label variable hv807a   "Date of biomarker Century Day Code (CDC)"
label variable hv201    "Source of drinking water"
label variable hv202    "Source of non-drinking water"
label variable hv201a   "NA - Water not available for at least a day last two weeks"
label variable hv204    "Time to get to water source (minutes)"
label variable hv205    "Type of toilet facility"
label variable hv206    "Has electricity"
label variable hv207    "Has radio"
label variable hv208    "Has television"
label variable hv209    "Has refrigerator"
label variable hv210    "Has bicycle"
label variable hv211    "Has motorcycle/scooter"
label variable hv212    "Has car/truck"
label variable hv213    "Main floor material"
label variable hv214    "Main wall material"
label variable hv215    "Main roof material"
label variable hv216    "Number of rooms used for sleeping"
label variable hv217    "Relationship structure"
label variable hv218    "Line number of head of household"
label variable hv219    "Sex of head of household"
label variable hv220    "Age of head of household"
label variable hv221    "Has telephone (land-line)"
label variable hv225    "Share toilet with other households"
label variable hv226    "Type of cooking fuel"
label variable hv227    "Has mosquito bed net for sleeping"
label variable hv228    "Children under 5 slept under mosquito bed net last night"
label variable hv235    "Location of source for water"
label variable hv238    "Number of households sharing toilet"
label variable hv238a   "Location of toilet facility"
label variable hv243a   "Has mobile telephone"
label variable hv243b   "Has watch"
label variable hv243c   "Has animal-drawn cart"
label variable hv243d   "Has boat with a motor/pinasse"
label variable hv243e   "Has a computer"
label variable hv244    "Owns land usable for agriculture"
label variable hv245    "Hectares of agricultural land (1 decimal)"
label variable hv246    "Owns livestock, herds or farm animals"
label variable hv246a   "Owns cattle"
label variable hv246b   "Owns cows/ bulls"
label variable hv246c   "Owns horses/ donkeys/ mules"
label variable hv246d   "Owns goats"
label variable hv246e   "Owns sheep"
label variable hv246f   "Owns chickens/poultry"
label variable hv246g   "Owns camels"
label variable hv246h   "Owns ducks/geeses"
label variable hv246i   "Owns rabbits"
label variable hv246j   "NA - Owns CS"
label variable hv246k   "NA - Owns CS"
label variable hv247    "Has bank account"
label variable hv270    "Wealth index combined"
label variable hv271    "Wealth index factor score combined (5 decimals)"
label variable hv270a   "Wealth index for urban/rural"
label variable hv271a   "Wealth index factor score for urban/rural (5 decimals)"
label variable hml1     "Number of mosquito bed nets"
label variable hml1a    "Number of mosquito bed nets with specific information"
label variable hml2     "Number of children under mosquito bed net previous night"
label variable hv222    "Type of cookstove"
label variable hv223    "Type of cooking fuel"
label variable shconces "Structure/Concession number"
label variable sh116g   "Has chair in traditional materials"
label variable sh116h   "Has cupboard/library"
label variable sh116i   "Has portable stove/cooker"
label variable sh116j   "Has gas/electric stove"
label variable sh116k   "Has improved stove"
label variable sh116l   "Has air conditioner"
label variable sh116m   "Has access to internet"
label variable sh116n   "Has solar panels"
label variable sh116o   "Has generator"
label variable sh116p   "Has parabolic antenna"
label variable sh117h   "Has plow"
label variable sh117i   "Has canoe"
label variable sh117j   "Has tractor"
label variable sh117k   "Has tiller"
label variable sh117l   "Has motorized seeder"
label variable sh117m   "Has tricycle motorcycle"
label variable sh117n   "Has moped/bike"
label variable sh117o   "Has motor pump"
label variable sh119    "Used mobile phone for financial transactions"
label variable hvidx_01 "Line number"
label variable hvidx_02 "Line number"
label variable hvidx_03 "Line number"
label variable hvidx_04 "Line number"
label variable hvidx_05 "Line number"
label variable hvidx_06 "Line number"
label variable hvidx_07 "Line number"
label variable hvidx_08 "Line number"
label variable hvidx_09 "Line number"
label variable hvidx_10 "Line number"
label variable hvidx_11 "Line number"
label variable hvidx_12 "Line number"
label variable hvidx_13 "Line number"
label variable hvidx_14 "Line number"
label variable hvidx_15 "Line number"
label variable hvidx_16 "Line number"
label variable hvidx_17 "Line number"
label variable hvidx_18 "Line number"
label variable hvidx_19 "Line number"
label variable hvidx_20 "Line number"
label variable hvidx_21 "Line number"
label variable hvidx_22 "Line number"
label variable hvidx_23 "Line number"
label variable hvidx_24 "Line number"
label variable hvidx_25 "Line number"
label variable hvidx_26 "Line number"
label variable hvidx_27 "Line number"
label variable hvidx_28 "Line number"
label variable hvidx_29 "Line number"
label variable hvidx_30 "Line number"
label variable hvidx_31 "Line number"
label variable hvidx_32 "Line number"
label variable hvidx_33 "Line number"
label variable hv101_01 "Relationship to head"
label variable hv101_02 "Relationship to head"
label variable hv101_03 "Relationship to head"
label variable hv101_04 "Relationship to head"
label variable hv101_05 "Relationship to head"
label variable hv101_06 "Relationship to head"
label variable hv101_07 "Relationship to head"
label variable hv101_08 "Relationship to head"
label variable hv101_09 "Relationship to head"
label variable hv101_10 "Relationship to head"
label variable hv101_11 "Relationship to head"
label variable hv101_12 "Relationship to head"
label variable hv101_13 "Relationship to head"
label variable hv101_14 "Relationship to head"
label variable hv101_15 "Relationship to head"
label variable hv101_16 "Relationship to head"
label variable hv101_17 "Relationship to head"
label variable hv101_18 "Relationship to head"
label variable hv101_19 "Relationship to head"
label variable hv101_20 "Relationship to head"
label variable hv101_21 "Relationship to head"
label variable hv101_22 "Relationship to head"
label variable hv101_23 "Relationship to head"
label variable hv101_24 "Relationship to head"
label variable hv101_25 "Relationship to head"
label variable hv101_26 "Relationship to head"
label variable hv101_27 "Relationship to head"
label variable hv101_28 "Relationship to head"
label variable hv101_29 "Relationship to head"
label variable hv101_30 "Relationship to head"
label variable hv101_31 "Relationship to head"
label variable hv101_32 "Relationship to head"
label variable hv101_33 "Relationship to head"
label variable hv102_01 "Usual resident"
label variable hv102_02 "Usual resident"
label variable hv102_03 "Usual resident"
label variable hv102_04 "Usual resident"
label variable hv102_05 "Usual resident"
label variable hv102_06 "Usual resident"
label variable hv102_07 "Usual resident"
label variable hv102_08 "Usual resident"
label variable hv102_09 "Usual resident"
label variable hv102_10 "Usual resident"
label variable hv102_11 "Usual resident"
label variable hv102_12 "Usual resident"
label variable hv102_13 "Usual resident"
label variable hv102_14 "Usual resident"
label variable hv102_15 "Usual resident"
label variable hv102_16 "Usual resident"
label variable hv102_17 "Usual resident"
label variable hv102_18 "Usual resident"
label variable hv102_19 "Usual resident"
label variable hv102_20 "Usual resident"
label variable hv102_21 "Usual resident"
label variable hv102_22 "Usual resident"
label variable hv102_23 "Usual resident"
label variable hv102_24 "Usual resident"
label variable hv102_25 "Usual resident"
label variable hv102_26 "Usual resident"
label variable hv102_27 "Usual resident"
label variable hv102_28 "Usual resident"
label variable hv102_29 "Usual resident"
label variable hv102_30 "Usual resident"
label variable hv102_31 "Usual resident"
label variable hv102_32 "Usual resident"
label variable hv102_33 "Usual resident"
label variable hv103_01 "Slept last night"
label variable hv103_02 "Slept last night"
label variable hv103_03 "Slept last night"
label variable hv103_04 "Slept last night"
label variable hv103_05 "Slept last night"
label variable hv103_06 "Slept last night"
label variable hv103_07 "Slept last night"
label variable hv103_08 "Slept last night"
label variable hv103_09 "Slept last night"
label variable hv103_10 "Slept last night"
label variable hv103_11 "Slept last night"
label variable hv103_12 "Slept last night"
label variable hv103_13 "Slept last night"
label variable hv103_14 "Slept last night"
label variable hv103_15 "Slept last night"
label variable hv103_16 "Slept last night"
label variable hv103_17 "Slept last night"
label variable hv103_18 "Slept last night"
label variable hv103_19 "Slept last night"
label variable hv103_20 "Slept last night"
label variable hv103_21 "Slept last night"
label variable hv103_22 "Slept last night"
label variable hv103_23 "Slept last night"
label variable hv103_24 "Slept last night"
label variable hv103_25 "Slept last night"
label variable hv103_26 "Slept last night"
label variable hv103_27 "Slept last night"
label variable hv103_28 "Slept last night"
label variable hv103_29 "Slept last night"
label variable hv103_30 "Slept last night"
label variable hv103_31 "Slept last night"
label variable hv103_32 "Slept last night"
label variable hv103_33 "Slept last night"
label variable hv104_01 "Sex of household member"
label variable hv104_02 "Sex of household member"
label variable hv104_03 "Sex of household member"
label variable hv104_04 "Sex of household member"
label variable hv104_05 "Sex of household member"
label variable hv104_06 "Sex of household member"
label variable hv104_07 "Sex of household member"
label variable hv104_08 "Sex of household member"
label variable hv104_09 "Sex of household member"
label variable hv104_10 "Sex of household member"
label variable hv104_11 "Sex of household member"
label variable hv104_12 "Sex of household member"
label variable hv104_13 "Sex of household member"
label variable hv104_14 "Sex of household member"
label variable hv104_15 "Sex of household member"
label variable hv104_16 "Sex of household member"
label variable hv104_17 "Sex of household member"
label variable hv104_18 "Sex of household member"
label variable hv104_19 "Sex of household member"
label variable hv104_20 "Sex of household member"
label variable hv104_21 "Sex of household member"
label variable hv104_22 "Sex of household member"
label variable hv104_23 "Sex of household member"
label variable hv104_24 "Sex of household member"
label variable hv104_25 "Sex of household member"
label variable hv104_26 "Sex of household member"
label variable hv104_27 "Sex of household member"
label variable hv104_28 "Sex of household member"
label variable hv104_29 "Sex of household member"
label variable hv104_30 "Sex of household member"
label variable hv104_31 "Sex of household member"
label variable hv104_32 "Sex of household member"
label variable hv104_33 "Sex of household member"
label variable hv105_01 "Age of household members"
label variable hv105_02 "Age of household members"
label variable hv105_03 "Age of household members"
label variable hv105_04 "Age of household members"
label variable hv105_05 "Age of household members"
label variable hv105_06 "Age of household members"
label variable hv105_07 "Age of household members"
label variable hv105_08 "Age of household members"
label variable hv105_09 "Age of household members"
label variable hv105_10 "Age of household members"
label variable hv105_11 "Age of household members"
label variable hv105_12 "Age of household members"
label variable hv105_13 "Age of household members"
label variable hv105_14 "Age of household members"
label variable hv105_15 "Age of household members"
label variable hv105_16 "Age of household members"
label variable hv105_17 "Age of household members"
label variable hv105_18 "Age of household members"
label variable hv105_19 "Age of household members"
label variable hv105_20 "Age of household members"
label variable hv105_21 "Age of household members"
label variable hv105_22 "Age of household members"
label variable hv105_23 "Age of household members"
label variable hv105_24 "Age of household members"
label variable hv105_25 "Age of household members"
label variable hv105_26 "Age of household members"
label variable hv105_27 "Age of household members"
label variable hv105_28 "Age of household members"
label variable hv105_29 "Age of household members"
label variable hv105_30 "Age of household members"
label variable hv105_31 "Age of household members"
label variable hv105_32 "Age of household members"
label variable hv105_33 "Age of household members"
label variable hv117_01 "Eligibility for female interview"
label variable hv117_02 "Eligibility for female interview"
label variable hv117_03 "Eligibility for female interview"
label variable hv117_04 "Eligibility for female interview"
label variable hv117_05 "Eligibility for female interview"
label variable hv117_06 "Eligibility for female interview"
label variable hv117_07 "Eligibility for female interview"
label variable hv117_08 "Eligibility for female interview"
label variable hv117_09 "Eligibility for female interview"
label variable hv117_10 "Eligibility for female interview"
label variable hv117_11 "Eligibility for female interview"
label variable hv117_12 "Eligibility for female interview"
label variable hv117_13 "Eligibility for female interview"
label variable hv117_14 "Eligibility for female interview"
label variable hv117_15 "Eligibility for female interview"
label variable hv117_16 "Eligibility for female interview"
label variable hv117_17 "Eligibility for female interview"
label variable hv117_18 "Eligibility for female interview"
label variable hv117_19 "Eligibility for female interview"
label variable hv117_20 "Eligibility for female interview"
label variable hv117_21 "Eligibility for female interview"
label variable hv117_22 "Eligibility for female interview"
label variable hv117_23 "Eligibility for female interview"
label variable hv117_24 "Eligibility for female interview"
label variable hv117_25 "Eligibility for female interview"
label variable hv117_26 "Eligibility for female interview"
label variable hv117_27 "Eligibility for female interview"
label variable hv117_28 "Eligibility for female interview"
label variable hv117_29 "Eligibility for female interview"
label variable hv117_30 "Eligibility for female interview"
label variable hv117_31 "Eligibility for female interview"
label variable hv117_32 "Eligibility for female interview"
label variable hv117_33 "Eligibility for female interview"
label variable hv120_01 "Children eligibility for height/weight and hemoglobin"
label variable hv120_02 "Children eligibility for height/weight and hemoglobin"
label variable hv120_03 "Children eligibility for height/weight and hemoglobin"
label variable hv120_04 "Children eligibility for height/weight and hemoglobin"
label variable hv120_05 "Children eligibility for height/weight and hemoglobin"
label variable hv120_06 "Children eligibility for height/weight and hemoglobin"
label variable hv120_07 "Children eligibility for height/weight and hemoglobin"
label variable hv120_08 "Children eligibility for height/weight and hemoglobin"
label variable hv120_09 "Children eligibility for height/weight and hemoglobin"
label variable hv120_10 "Children eligibility for height/weight and hemoglobin"
label variable hv120_11 "Children eligibility for height/weight and hemoglobin"
label variable hv120_12 "Children eligibility for height/weight and hemoglobin"
label variable hv120_13 "Children eligibility for height/weight and hemoglobin"
label variable hv120_14 "Children eligibility for height/weight and hemoglobin"
label variable hv120_15 "Children eligibility for height/weight and hemoglobin"
label variable hv120_16 "Children eligibility for height/weight and hemoglobin"
label variable hv120_17 "Children eligibility for height/weight and hemoglobin"
label variable hv120_18 "Children eligibility for height/weight and hemoglobin"
label variable hv120_19 "Children eligibility for height/weight and hemoglobin"
label variable hv120_20 "Children eligibility for height/weight and hemoglobin"
label variable hv120_21 "Children eligibility for height/weight and hemoglobin"
label variable hv120_22 "Children eligibility for height/weight and hemoglobin"
label variable hv120_23 "Children eligibility for height/weight and hemoglobin"
label variable hv120_24 "Children eligibility for height/weight and hemoglobin"
label variable hv120_25 "Children eligibility for height/weight and hemoglobin"
label variable hv120_26 "Children eligibility for height/weight and hemoglobin"
label variable hv120_27 "Children eligibility for height/weight and hemoglobin"
label variable hv120_28 "Children eligibility for height/weight and hemoglobin"
label variable hv120_29 "Children eligibility for height/weight and hemoglobin"
label variable hv120_30 "Children eligibility for height/weight and hemoglobin"
label variable hv120_31 "Children eligibility for height/weight and hemoglobin"
label variable hv120_32 "Children eligibility for height/weight and hemoglobin"
label variable hv120_33 "Children eligibility for height/weight and hemoglobin"
label variable hc0_1    "Index to Household Schedule"
label variable hc0_2    "Index to Household Schedule"
label variable hc0_3    "Index to Household Schedule"
label variable hc0_4    "Index to Household Schedule"
label variable hc0_5    "Index to Household Schedule"
label variable hc0_6    "Index to Household Schedule"
label variable hc0_7    "Index to Household Schedule"
label variable hc1_1    "Child's age in months"
label variable hc1_2    "Child's age in months"
label variable hc1_3    "Child's age in months"
label variable hc1_4    "Child's age in months"
label variable hc1_5    "Child's age in months"
label variable hc1_6    "Child's age in months"
label variable hc1_7    "Child's age in months"
label variable hc1a_1   "Child's age in days"
label variable hc1a_2   "Child's age in days"
label variable hc1a_3   "Child's age in days"
label variable hc1a_4   "Child's age in days"
label variable hc1a_5   "Child's age in days"
label variable hc1a_6   "Child's age in days"
label variable hc1a_7   "Child's age in days"
label variable hc16_1   "Day of birth"
label variable hc16_2   "Day of birth"
label variable hc16_3   "Day of birth"
label variable hc16_4   "Day of birth"
label variable hc16_5   "Day of birth"
label variable hc16_6   "Day of birth"
label variable hc16_7   "Day of birth"
label variable hc17_1   "Date measured (day)"
label variable hc17_2   "Date measured (day)"
label variable hc17_3   "Date measured (day)"
label variable hc17_4   "Date measured (day)"
label variable hc17_5   "Date measured (day)"
label variable hc17_6   "Date measured (day)"
label variable hc17_7   "Date measured (day)"
label variable hc18_1   "Date measured (month)"
label variable hc18_2   "Date measured (month)"
label variable hc18_3   "Date measured (month)"
label variable hc18_4   "Date measured (month)"
label variable hc18_5   "Date measured (month)"
label variable hc18_6   "Date measured (month)"
label variable hc18_7   "Date measured (month)"
label variable hc19_1   "Date measured (year)"
label variable hc19_2   "Date measured (year)"
label variable hc19_3   "Date measured (year)"
label variable hc19_4   "Date measured (year)"
label variable hc19_5   "Date measured (year)"
label variable hc19_6   "Date measured (year)"
label variable hc19_7   "Date measured (year)"
label variable hc20_1   "Century Day Code (CDC) of measurement"
label variable hc20_2   "Century Day Code (CDC) of measurement"
label variable hc20_3   "Century Day Code (CDC) of measurement"
label variable hc20_4   "Century Day Code (CDC) of measurement"
label variable hc20_5   "Century Day Code (CDC) of measurement"
label variable hc20_6   "Century Day Code (CDC) of measurement"
label variable hc20_7   "Century Day Code (CDC) of measurement"
label variable hc21_1   "Fieldworker measurer code"
label variable hc21_2   "Fieldworker measurer code"
label variable hc21_3   "Fieldworker measurer code"
label variable hc21_4   "Fieldworker measurer code"
label variable hc21_5   "Fieldworker measurer code"
label variable hc21_6   "Fieldworker measurer code"
label variable hc21_7   "Fieldworker measurer code"
label variable hc27_1   "Sex"
label variable hc27_2   "Sex"
label variable hc27_3   "Sex"
label variable hc27_4   "Sex"
label variable hc27_5   "Sex"
label variable hc27_6   "Sex"
label variable hc27_7   "Sex"
label variable hc30_1   "Month of birth"
label variable hc30_2   "Month of birth"
label variable hc30_3   "Month of birth"
label variable hc30_4   "Month of birth"
label variable hc30_5   "Month of birth"
label variable hc30_6   "Month of birth"
label variable hc30_7   "Month of birth"
label variable hc31_1   "Year of birth"
label variable hc31_2   "Year of birth"
label variable hc31_3   "Year of birth"
label variable hc31_4   "Year of birth"
label variable hc31_5   "Year of birth"
label variable hc31_6   "Year of birth"
label variable hc31_7   "Year of birth"
label variable hc32_1   "Date of birth (CMC)"
label variable hc32_2   "Date of birth (CMC)"
label variable hc32_3   "Date of birth (CMC)"
label variable hc32_4   "Date of birth (CMC)"
label variable hc32_5   "Date of birth (CMC)"
label variable hc32_6   "Date of birth (CMC)"
label variable hc32_7   "Date of birth (CMC)"
label variable hc32a_1  "Century Day Code (CDC) of birth"
label variable hc32a_2  "Century Day Code (CDC) of birth"
label variable hc32a_3  "Century Day Code (CDC) of birth"
label variable hc32a_4  "Century Day Code (CDC) of birth"
label variable hc32a_5  "Century Day Code (CDC) of birth"
label variable hc32a_6  "Century Day Code (CDC) of birth"
label variable hc32a_7  "Century Day Code (CDC) of birth"
label variable hc33_1   "Completeness of HC32 information"
label variable hc33_2   "Completeness of HC32 information"
label variable hc33_3   "Completeness of HC32 information"
label variable hc33_4   "Completeness of HC32 information"
label variable hc33_5   "Completeness of HC32 information"
label variable hc33_6   "Completeness of HC32 information"
label variable hc33_7   "Completeness of HC32 information"
label variable hc51_1   "Line number of parent/caretaker"
label variable hc51_2   "Line number of parent/caretaker"
label variable hc51_3   "Line number of parent/caretaker"
label variable hc51_4   "Line number of parent/caretaker"
label variable hc51_5   "Line number of parent/caretaker"
label variable hc51_6   "Line number of parent/caretaker"
label variable hc51_7   "Line number of parent/caretaker"
label variable hc52_1   "Read consent statement - hemoglobin"
label variable hc52_2   "Read consent statement - hemoglobin"
label variable hc52_3   "Read consent statement - hemoglobin"
label variable hc52_4   "Read consent statement - hemoglobin"
label variable hc52_5   "Read consent statement - hemoglobin"
label variable hc52_6   "Read consent statement - hemoglobin"
label variable hc52_7   "Read consent statement - hemoglobin"
label variable hc53_1   "Hemoglobin level (g/dl - 1 decimal)"
label variable hc53_2   "Hemoglobin level (g/dl - 1 decimal)"
label variable hc53_3   "Hemoglobin level (g/dl - 1 decimal)"
label variable hc53_4   "Hemoglobin level (g/dl - 1 decimal)"
label variable hc53_5   "Hemoglobin level (g/dl - 1 decimal)"
label variable hc53_6   "Hemoglobin level (g/dl - 1 decimal)"
label variable hc53_7   "Hemoglobin level (g/dl - 1 decimal)"
label variable hc55_1   "Result of measurement - hemoglobin"
label variable hc55_2   "Result of measurement - hemoglobin"
label variable hc55_3   "Result of measurement - hemoglobin"
label variable hc55_4   "Result of measurement - hemoglobin"
label variable hc55_5   "Result of measurement - hemoglobin"
label variable hc55_6   "Result of measurement - hemoglobin"
label variable hc55_7   "Result of measurement - hemoglobin"
label variable hc56_1   "Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
label variable hc56_2   "Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
label variable hc56_3   "Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
label variable hc56_4   "Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
label variable hc56_5   "Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
label variable hc56_6   "Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
label variable hc56_7   "Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
label variable hc57_1   "Anemia level"
label variable hc57_2   "Anemia level"
label variable hc57_3   "Anemia level"
label variable hc57_4   "Anemia level"
label variable hc57_5   "Anemia level"
label variable hc57_6   "Anemia level"
label variable hc57_7   "Anemia level"
label variable hc58_1   "NA - Agrees to referral - anemia"
label variable hc58_2   "NA - Agrees to referral - anemia"
label variable hc58_3   "NA - Agrees to referral - anemia"
label variable hc58_4   "NA - Agrees to referral - anemia"
label variable hc58_5   "NA - Agrees to referral - anemia"
label variable hc58_6   "NA - Agrees to referral - anemia"
label variable hc58_7   "NA - Agrees to referral - anemia"
label variable hc60_1   "Mother's line number (woman's questionnaire)"
label variable hc60_2   "Mother's line number (woman's questionnaire)"
label variable hc60_3   "Mother's line number (woman's questionnaire)"
label variable hc60_4   "Mother's line number (woman's questionnaire)"
label variable hc60_5   "Mother's line number (woman's questionnaire)"
label variable hc60_6   "Mother's line number (woman's questionnaire)"
label variable hc60_7   "Mother's line number (woman's questionnaire)"
label variable hc61_1   "Mother's highest educational level"
label variable hc61_2   "Mother's highest educational level"
label variable hc61_3   "Mother's highest educational level"
label variable hc61_4   "Mother's highest educational level"
label variable hc61_5   "Mother's highest educational level"
label variable hc61_6   "Mother's highest educational level"
label variable hc61_7   "Mother's highest educational level"
label variable hc62_1   "Mother's highest year of education"
label variable hc62_2   "Mother's highest year of education"
label variable hc62_3   "Mother's highest year of education"
label variable hc62_4   "Mother's highest year of education"
label variable hc62_5   "Mother's highest year of education"
label variable hc62_6   "Mother's highest year of education"
label variable hc62_7   "Mother's highest year of education"
label variable hc63_1   "Preceding birth interval (months)"
label variable hc63_2   "Preceding birth interval (months)"
label variable hc63_3   "Preceding birth interval (months)"
label variable hc63_4   "Preceding birth interval (months)"
label variable hc63_5   "Preceding birth interval (months)"
label variable hc63_6   "Preceding birth interval (months)"
label variable hc63_7   "Preceding birth interval (months)"
label variable hc64_1   "Birth order number"
label variable hc64_2   "Birth order number"
label variable hc64_3   "Birth order number"
label variable hc64_4   "Birth order number"
label variable hc64_5   "Birth order number"
label variable hc64_6   "Birth order number"
label variable hc64_7   "Birth order number"
label variable hc68_1   "Mother's highest educational level (for preliminary and final report)"
label variable hc68_2   "Mother's highest educational level (for preliminary and final report)"
label variable hc68_3   "Mother's highest educational level (for preliminary and final report)"
label variable hc68_4   "Mother's highest educational level (for preliminary and final report)"
label variable hc68_5   "Mother's highest educational level (for preliminary and final report)"
label variable hc68_6   "Mother's highest educational level (for preliminary and final report)"
label variable hc68_7   "Mother's highest educational level (for preliminary and final report)"
label variable hmlidx_1 "Mosquito Bed Net Designation Number"
label variable hmlidx_2 "Mosquito Bed Net Designation Number"
label variable hmlidx_3 "Mosquito Bed Net Designation Number"
label variable hmlidx_4 "Mosquito Bed Net Designation Number"
label variable hmlidx_5 "Mosquito Bed Net Designation Number"
label variable hmlidx_6 "Mosquito Bed Net Designation Number"
label variable hmlidx_7 "Mosquito Bed Net Designation Number"
label variable hml3_1   "Net observed by interviewer"
label variable hml3_2   "Net observed by interviewer"
label variable hml3_3   "Net observed by interviewer"
label variable hml3_4   "Net observed by interviewer"
label variable hml3_5   "Net observed by interviewer"
label variable hml3_6   "Net observed by interviewer"
label variable hml3_7   "Net observed by interviewer"
label variable hml4_1   "Months ago net obtained"
label variable hml4_2   "Months ago net obtained"
label variable hml4_3   "Months ago net obtained"
label variable hml4_4   "Months ago net obtained"
label variable hml4_5   "Months ago net obtained"
label variable hml4_6   "Months ago net obtained"
label variable hml4_7   "Months ago net obtained"
label variable hml5_1   "NA - Net treated with insecticide when bought"
label variable hml5_2   "NA - Net treated with insecticide when bought"
label variable hml5_3   "NA - Net treated with insecticide when bought"
label variable hml5_4   "NA - Net treated with insecticide when bought"
label variable hml5_5   "NA - Net treated with insecticide when bought"
label variable hml5_6   "NA - Net treated with insecticide when bought"
label variable hml5_7   "NA - Net treated with insecticide when bought"
label variable hml6_1   "Net treatment status"
label variable hml6_2   "Net treatment status"
label variable hml6_3   "Net treatment status"
label variable hml6_4   "Net treatment status"
label variable hml6_5   "Net treatment status"
label variable hml6_6   "Net treatment status"
label variable hml6_7   "Net treatment status"
label variable hml7_1   "Brand of net"
label variable hml7_2   "Brand of net"
label variable hml7_3   "Brand of net"
label variable hml7_4   "Brand of net"
label variable hml7_5   "Brand of net"
label variable hml7_6   "Brand of net"
label variable hml7_7   "Brand of net"
label variable hml8_1   "Net treated since received"
label variable hml8_2   "Net treated since received"
label variable hml8_3   "Net treated since received"
label variable hml8_4   "Net treated since received"
label variable hml8_5   "Net treated since received"
label variable hml8_6   "Net treated since received"
label variable hml8_7   "Net treated since received"
label variable hml9_1   "NA - Time since last re-treatment (months)"
label variable hml9_2   "NA - Time since last re-treatment (months)"
label variable hml9_3   "NA - Time since last re-treatment (months)"
label variable hml9_4   "NA - Time since last re-treatment (months)"
label variable hml9_5   "NA - Time since last re-treatment (months)"
label variable hml9_6   "NA - Time since last re-treatment (months)"
label variable hml9_7   "NA - Time since last re-treatment (months)"
label variable hml10_1  "Insecticide-Treated Net (ITN)"
label variable hml10_2  "Insecticide-Treated Net (ITN)"
label variable hml10_3  "Insecticide-Treated Net (ITN)"
label variable hml10_4  "Insecticide-Treated Net (ITN)"
label variable hml10_5  "Insecticide-Treated Net (ITN)"
label variable hml10_6  "Insecticide-Treated Net (ITN)"
label variable hml10_7  "Insecticide-Treated Net (ITN)"
label variable hml11_1  "Number of persons who slept under this net"
label variable hml11_2  "Number of persons who slept under this net"
label variable hml11_3  "Number of persons who slept under this net"
label variable hml11_4  "Number of persons who slept under this net"
label variable hml11_5  "Number of persons who slept under this net"
label variable hml11_6  "Number of persons who slept under this net"
label variable hml11_7  "Number of persons who slept under this net"
label variable hml21_1  "Someone slept under this net last night"
label variable hml21_2  "Someone slept under this net last night"
label variable hml21_3  "Someone slept under this net last night"
label variable hml21_4  "Someone slept under this net last night"
label variable hml21_5  "Someone slept under this net last night"
label variable hml21_6  "Someone slept under this net last night"
label variable hml21_7  "Someone slept under this net last night"
label variable hmla_1   "Line number of person who slept in this net"
label variable hmla_2   "Line number of person who slept in this net"
label variable hmla_3   "Line number of person who slept in this net"
label variable hmla_4   "Line number of person who slept in this net"
label variable hmla_5   "Line number of person who slept in this net"
label variable hmla_6   "Line number of person who slept in this net"
label variable hmla_7   "Line number of person who slept in this net"
label variable hmlb_1   "Line number of person who slept in this net"
label variable hmlb_2   "Line number of person who slept in this net"
label variable hmlb_3   "Line number of person who slept in this net"
label variable hmlb_4   "Line number of person who slept in this net"
label variable hmlb_5   "Line number of person who slept in this net"
label variable hmlb_6   "Line number of person who slept in this net"
label variable hmlb_7   "Line number of person who slept in this net"
label variable hmlc_1   "Line number of person who slept in this net"
label variable hmlc_2   "Line number of person who slept in this net"
label variable hmlc_3   "Line number of person who slept in this net"
label variable hmlc_4   "Line number of person who slept in this net"
label variable hmlc_5   "Line number of person who slept in this net"
label variable hmlc_6   "Line number of person who slept in this net"
label variable hmlc_7   "Line number of person who slept in this net"
label variable hmld_1   "Line number of person who slept in this net"
label variable hmld_2   "Line number of person who slept in this net"
label variable hmld_3   "Line number of person who slept in this net"
label variable hmld_4   "Line number of person who slept in this net"
label variable hmld_5   "Line number of person who slept in this net"
label variable hmld_6   "Line number of person who slept in this net"
label variable hmld_7   "Line number of person who slept in this net"
label variable hmle_1   "NA - Line number of person who slept in this net"
label variable hmle_2   "NA - Line number of person who slept in this net"
label variable hmle_3   "NA - Line number of person who slept in this net"
label variable hmle_4   "NA - Line number of person who slept in this net"
label variable hmle_5   "NA - Line number of person who slept in this net"
label variable hmle_6   "NA - Line number of person who slept in this net"
label variable hmle_7   "NA - Line number of person who slept in this net"
label variable hml22_1  "Obtained net from campaign, antenatal or immunization visit"
label variable hml22_2  "Obtained net from campaign, antenatal or immunization visit"
label variable hml22_3  "Obtained net from campaign, antenatal or immunization visit"
label variable hml22_4  "Obtained net from campaign, antenatal or immunization visit"
label variable hml22_5  "Obtained net from campaign, antenatal or immunization visit"
label variable hml22_6  "Obtained net from campaign, antenatal or immunization visit"
label variable hml22_7  "Obtained net from campaign, antenatal or immunization visit"
label variable hml23_1  "Place where net was obtained"
label variable hml23_2  "Place where net was obtained"
label variable hml23_3  "Place where net was obtained"
label variable hml23_4  "Place where net was obtained"
label variable hml23_5  "Place where net was obtained"
label variable hml23_6  "Place where net was obtained"
label variable hml23_7  "Place where net was obtained"
label variable sh130_1  "Reason for not using the net"
label variable sh130_2  "Reason for not using the net"
label variable sh130_3  "Reason for not using the net"
label variable sh130_4  "Reason for not using the net"
label variable sh130_5  "Reason for not using the net"
label variable sh130_6  "Reason for not using the net"
label variable sh130_7  "Reason for not using the net"
label variable hmhidx_01 "Index to Household Schedule"
label variable hmhidx_02 "Index to Household Schedule"
label variable hmhidx_03 "Index to Household Schedule"
label variable hmhidx_04 "Index to Household Schedule"
label variable hmhidx_05 "Index to Household Schedule"
label variable hmhidx_06 "Index to Household Schedule"
label variable hmhidx_07 "Index to Household Schedule"
label variable hmhidx_08 "Index to Household Schedule"
label variable hmhidx_09 "Index to Household Schedule"
label variable hmhidx_10 "Index to Household Schedule"
label variable hmhidx_11 "Index to Household Schedule"
label variable hmhidx_12 "Index to Household Schedule"
label variable hmhidx_13 "Index to Household Schedule"
label variable hmhidx_14 "Index to Household Schedule"
label variable hmhidx_15 "Index to Household Schedule"
label variable hmhidx_16 "Index to Household Schedule"
label variable hmhidx_17 "Index to Household Schedule"
label variable hmhidx_18 "Index to Household Schedule"
label variable hmhidx_19 "Index to Household Schedule"
label variable hmhidx_20 "Index to Household Schedule"
label variable hmhidx_21 "Index to Household Schedule"
label variable hmhidx_22 "Index to Household Schedule"
label variable hmhidx_23 "Index to Household Schedule"
label variable hmhidx_24 "Index to Household Schedule"
label variable hmhidx_25 "Index to Household Schedule"
label variable hmhidx_26 "Index to Household Schedule"
label variable hmhidx_27 "Index to Household Schedule"
label variable hmhidx_28 "Index to Household Schedule"
label variable hmhidx_29 "Index to Household Schedule"
label variable hmhidx_30 "Index to Household Schedule"
label variable hmhidx_31 "Index to Household Schedule"
label variable hmhidx_32 "Index to Household Schedule"
label variable hmhidx_33 "Index to Household Schedule"
label variable hml12_01 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_02 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_03 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_04 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_05 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_06 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_07 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_08 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_09 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_10 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_11 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_12 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_13 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_14 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_15 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_16 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_17 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_18 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_19 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_20 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_21 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_22 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_23 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_24 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_25 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_26 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_27 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_28 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_29 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_30 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_31 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_32 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_33 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml13_01 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_02 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_03 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_04 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_05 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_06 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_07 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_08 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_09 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_10 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_11 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_12 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_13 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_14 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_15 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_16 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_17 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_18 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_19 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_20 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_21 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_22 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_23 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_24 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_25 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_26 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_27 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_28 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_29 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_30 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_31 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_32 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_33 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml14_01 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_02 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_03 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_04 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_05 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_06 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_07 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_08 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_09 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_10 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_11 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_12 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_13 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_14 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_15 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_16 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_17 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_18 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_19 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_20 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_21 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_22 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_23 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_24 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_25 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_26 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_27 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_28 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_29 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_30 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_31 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_32 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_33 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml15_01 "Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_02 "Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_03 "Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_04 "Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_05 "Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_06 "Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_07 "Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_08 "Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_09 "Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_10 "Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_11 "Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_12 "Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_13 "Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_14 "Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_15 "Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_16 "Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_17 "Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_18 "Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_19 "Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_20 "Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_21 "Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_22 "Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_23 "Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_24 "Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_25 "Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_26 "Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_27 "Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_28 "Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_29 "Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_30 "Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_31 "Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_32 "Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_33 "Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml16_01 "Corrected age from Individual file"
label variable hml16_02 "Corrected age from Individual file"
label variable hml16_03 "Corrected age from Individual file"
label variable hml16_04 "Corrected age from Individual file"
label variable hml16_05 "Corrected age from Individual file"
label variable hml16_06 "Corrected age from Individual file"
label variable hml16_07 "Corrected age from Individual file"
label variable hml16_08 "Corrected age from Individual file"
label variable hml16_09 "Corrected age from Individual file"
label variable hml16_10 "Corrected age from Individual file"
label variable hml16_11 "Corrected age from Individual file"
label variable hml16_12 "Corrected age from Individual file"
label variable hml16_13 "Corrected age from Individual file"
label variable hml16_14 "Corrected age from Individual file"
label variable hml16_15 "Corrected age from Individual file"
label variable hml16_16 "Corrected age from Individual file"
label variable hml16_17 "Corrected age from Individual file"
label variable hml16_18 "Corrected age from Individual file"
label variable hml16_19 "Corrected age from Individual file"
label variable hml16_20 "Corrected age from Individual file"
label variable hml16_21 "Corrected age from Individual file"
label variable hml16_22 "Corrected age from Individual file"
label variable hml16_23 "Corrected age from Individual file"
label variable hml16_24 "Corrected age from Individual file"
label variable hml16_25 "Corrected age from Individual file"
label variable hml16_26 "Corrected age from Individual file"
label variable hml16_27 "Corrected age from Individual file"
label variable hml16_28 "Corrected age from Individual file"
label variable hml16_29 "Corrected age from Individual file"
label variable hml16_30 "Corrected age from Individual file"
label variable hml16_31 "Corrected age from Individual file"
label variable hml16_32 "Corrected age from Individual file"
label variable hml16_33 "Corrected age from Individual file"
label variable hml16a_01 "Age in months (for children)"
label variable hml16a_02 "Age in months (for children)"
label variable hml16a_03 "Age in months (for children)"
label variable hml16a_04 "Age in months (for children)"
label variable hml16a_05 "Age in months (for children)"
label variable hml16a_06 "Age in months (for children)"
label variable hml16a_07 "Age in months (for children)"
label variable hml16a_08 "Age in months (for children)"
label variable hml16a_09 "Age in months (for children)"
label variable hml16a_10 "Age in months (for children)"
label variable hml16a_11 "Age in months (for children)"
label variable hml16a_12 "Age in months (for children)"
label variable hml16a_13 "Age in months (for children)"
label variable hml16a_14 "Age in months (for children)"
label variable hml16a_15 "Age in months (for children)"
label variable hml16a_16 "Age in months (for children)"
label variable hml16a_17 "Age in months (for children)"
label variable hml16a_18 "Age in months (for children)"
label variable hml16a_19 "Age in months (for children)"
label variable hml16a_20 "Age in months (for children)"
label variable hml16a_21 "Age in months (for children)"
label variable hml16a_22 "Age in months (for children)"
label variable hml16a_23 "Age in months (for children)"
label variable hml16a_24 "Age in months (for children)"
label variable hml16a_25 "Age in months (for children)"
label variable hml16a_26 "Age in months (for children)"
label variable hml16a_27 "Age in months (for children)"
label variable hml16a_28 "Age in months (for children)"
label variable hml16a_29 "Age in months (for children)"
label variable hml16a_30 "Age in months (for children)"
label variable hml16a_31 "Age in months (for children)"
label variable hml16a_32 "Age in months (for children)"
label variable hml16a_33 "Age in months (for children)"
label variable hml17_01 "Flag for age from Individual file"
label variable hml17_02 "Flag for age from Individual file"
label variable hml17_03 "Flag for age from Individual file"
label variable hml17_04 "Flag for age from Individual file"
label variable hml17_05 "Flag for age from Individual file"
label variable hml17_06 "Flag for age from Individual file"
label variable hml17_07 "Flag for age from Individual file"
label variable hml17_08 "Flag for age from Individual file"
label variable hml17_09 "Flag for age from Individual file"
label variable hml17_10 "Flag for age from Individual file"
label variable hml17_11 "Flag for age from Individual file"
label variable hml17_12 "Flag for age from Individual file"
label variable hml17_13 "Flag for age from Individual file"
label variable hml17_14 "Flag for age from Individual file"
label variable hml17_15 "Flag for age from Individual file"
label variable hml17_16 "Flag for age from Individual file"
label variable hml17_17 "Flag for age from Individual file"
label variable hml17_18 "Flag for age from Individual file"
label variable hml17_19 "Flag for age from Individual file"
label variable hml17_20 "Flag for age from Individual file"
label variable hml17_21 "Flag for age from Individual file"
label variable hml17_22 "Flag for age from Individual file"
label variable hml17_23 "Flag for age from Individual file"
label variable hml17_24 "Flag for age from Individual file"
label variable hml17_25 "Flag for age from Individual file"
label variable hml17_26 "Flag for age from Individual file"
label variable hml17_27 "Flag for age from Individual file"
label variable hml17_28 "Flag for age from Individual file"
label variable hml17_29 "Flag for age from Individual file"
label variable hml17_30 "Flag for age from Individual file"
label variable hml17_31 "Flag for age from Individual file"
label variable hml17_32 "Flag for age from Individual file"
label variable hml17_33 "Flag for age from Individual file"
label variable hml18_01 "Pregnancy status from Individual file"
label variable hml18_02 "Pregnancy status from Individual file"
label variable hml18_03 "Pregnancy status from Individual file"
label variable hml18_04 "Pregnancy status from Individual file"
label variable hml18_05 "Pregnancy status from Individual file"
label variable hml18_06 "Pregnancy status from Individual file"
label variable hml18_07 "Pregnancy status from Individual file"
label variable hml18_08 "Pregnancy status from Individual file"
label variable hml18_09 "Pregnancy status from Individual file"
label variable hml18_10 "Pregnancy status from Individual file"
label variable hml18_11 "Pregnancy status from Individual file"
label variable hml18_12 "Pregnancy status from Individual file"
label variable hml18_13 "Pregnancy status from Individual file"
label variable hml18_14 "Pregnancy status from Individual file"
label variable hml18_15 "Pregnancy status from Individual file"
label variable hml18_16 "Pregnancy status from Individual file"
label variable hml18_17 "Pregnancy status from Individual file"
label variable hml18_18 "Pregnancy status from Individual file"
label variable hml18_19 "Pregnancy status from Individual file"
label variable hml18_20 "Pregnancy status from Individual file"
label variable hml18_21 "Pregnancy status from Individual file"
label variable hml18_22 "Pregnancy status from Individual file"
label variable hml18_23 "Pregnancy status from Individual file"
label variable hml18_24 "Pregnancy status from Individual file"
label variable hml18_25 "Pregnancy status from Individual file"
label variable hml18_26 "Pregnancy status from Individual file"
label variable hml18_27 "Pregnancy status from Individual file"
label variable hml18_28 "Pregnancy status from Individual file"
label variable hml18_29 "Pregnancy status from Individual file"
label variable hml18_30 "Pregnancy status from Individual file"
label variable hml18_31 "Pregnancy status from Individual file"
label variable hml18_32 "Pregnancy status from Individual file"
label variable hml18_33 "Pregnancy status from Individual file"
label variable hml19_01 "Person slept under an ever-treated net"
label variable hml19_02 "Person slept under an ever-treated net"
label variable hml19_03 "Person slept under an ever-treated net"
label variable hml19_04 "Person slept under an ever-treated net"
label variable hml19_05 "Person slept under an ever-treated net"
label variable hml19_06 "Person slept under an ever-treated net"
label variable hml19_07 "Person slept under an ever-treated net"
label variable hml19_08 "Person slept under an ever-treated net"
label variable hml19_09 "Person slept under an ever-treated net"
label variable hml19_10 "Person slept under an ever-treated net"
label variable hml19_11 "Person slept under an ever-treated net"
label variable hml19_12 "Person slept under an ever-treated net"
label variable hml19_13 "Person slept under an ever-treated net"
label variable hml19_14 "Person slept under an ever-treated net"
label variable hml19_15 "Person slept under an ever-treated net"
label variable hml19_16 "Person slept under an ever-treated net"
label variable hml19_17 "Person slept under an ever-treated net"
label variable hml19_18 "Person slept under an ever-treated net"
label variable hml19_19 "Person slept under an ever-treated net"
label variable hml19_20 "Person slept under an ever-treated net"
label variable hml19_21 "Person slept under an ever-treated net"
label variable hml19_22 "Person slept under an ever-treated net"
label variable hml19_23 "Person slept under an ever-treated net"
label variable hml19_24 "Person slept under an ever-treated net"
label variable hml19_25 "Person slept under an ever-treated net"
label variable hml19_26 "Person slept under an ever-treated net"
label variable hml19_27 "Person slept under an ever-treated net"
label variable hml19_28 "Person slept under an ever-treated net"
label variable hml19_29 "Person slept under an ever-treated net"
label variable hml19_30 "Person slept under an ever-treated net"
label variable hml19_31 "Person slept under an ever-treated net"
label variable hml19_32 "Person slept under an ever-treated net"
label variable hml19_33 "Person slept under an ever-treated net"
label variable hml20_01 "Person slept under an LLIN net"
label variable hml20_02 "Person slept under an LLIN net"
label variable hml20_03 "Person slept under an LLIN net"
label variable hml20_04 "Person slept under an LLIN net"
label variable hml20_05 "Person slept under an LLIN net"
label variable hml20_06 "Person slept under an LLIN net"
label variable hml20_07 "Person slept under an LLIN net"
label variable hml20_08 "Person slept under an LLIN net"
label variable hml20_09 "Person slept under an LLIN net"
label variable hml20_10 "Person slept under an LLIN net"
label variable hml20_11 "Person slept under an LLIN net"
label variable hml20_12 "Person slept under an LLIN net"
label variable hml20_13 "Person slept under an LLIN net"
label variable hml20_14 "Person slept under an LLIN net"
label variable hml20_15 "Person slept under an LLIN net"
label variable hml20_16 "Person slept under an LLIN net"
label variable hml20_17 "Person slept under an LLIN net"
label variable hml20_18 "Person slept under an LLIN net"
label variable hml20_19 "Person slept under an LLIN net"
label variable hml20_20 "Person slept under an LLIN net"
label variable hml20_21 "Person slept under an LLIN net"
label variable hml20_22 "Person slept under an LLIN net"
label variable hml20_23 "Person slept under an LLIN net"
label variable hml20_24 "Person slept under an LLIN net"
label variable hml20_25 "Person slept under an LLIN net"
label variable hml20_26 "Person slept under an LLIN net"
label variable hml20_27 "Person slept under an LLIN net"
label variable hml20_28 "Person slept under an LLIN net"
label variable hml20_29 "Person slept under an LLIN net"
label variable hml20_30 "Person slept under an LLIN net"
label variable hml20_31 "Person slept under an LLIN net"
label variable hml20_32 "Person slept under an LLIN net"
label variable hml20_33 "Person slept under an LLIN net"
label variable hml30_01 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_02 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_03 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_04 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_05 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_06 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_07 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_08 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_09 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_10 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_11 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_12 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_13 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_14 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_15 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_16 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_17 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_18 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_19 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_20 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_21 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_22 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_23 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_24 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_25 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_26 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_27 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_28 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_29 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_30 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_31 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_32 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_33 "Line number of parent/caretaker (for malaria testing)"
label variable hml31_01 "Read consent statement for malaria"
label variable hml31_02 "Read consent statement for malaria"
label variable hml31_03 "Read consent statement for malaria"
label variable hml31_04 "Read consent statement for malaria"
label variable hml31_05 "Read consent statement for malaria"
label variable hml31_06 "Read consent statement for malaria"
label variable hml31_07 "Read consent statement for malaria"
label variable hml31_08 "Read consent statement for malaria"
label variable hml31_09 "Read consent statement for malaria"
label variable hml31_10 "Read consent statement for malaria"
label variable hml31_11 "Read consent statement for malaria"
label variable hml31_12 "Read consent statement for malaria"
label variable hml31_13 "Read consent statement for malaria"
label variable hml31_14 "Read consent statement for malaria"
label variable hml31_15 "Read consent statement for malaria"
label variable hml31_16 "Read consent statement for malaria"
label variable hml31_17 "Read consent statement for malaria"
label variable hml31_18 "Read consent statement for malaria"
label variable hml31_19 "Read consent statement for malaria"
label variable hml31_20 "Read consent statement for malaria"
label variable hml31_21 "Read consent statement for malaria"
label variable hml31_22 "Read consent statement for malaria"
label variable hml31_23 "Read consent statement for malaria"
label variable hml31_24 "Read consent statement for malaria"
label variable hml31_25 "Read consent statement for malaria"
label variable hml31_26 "Read consent statement for malaria"
label variable hml31_27 "Read consent statement for malaria"
label variable hml31_28 "Read consent statement for malaria"
label variable hml31_29 "Read consent statement for malaria"
label variable hml31_30 "Read consent statement for malaria"
label variable hml31_31 "Read consent statement for malaria"
label variable hml31_32 "Read consent statement for malaria"
label variable hml31_33 "Read consent statement for malaria"
label variable hml32_01 "NA - Final result of malaria from blood smear test"
label variable hml32_02 "NA - Final result of malaria from blood smear test"
label variable hml32_03 "NA - Final result of malaria from blood smear test"
label variable hml32_04 "NA - Final result of malaria from blood smear test"
label variable hml32_05 "NA - Final result of malaria from blood smear test"
label variable hml32_06 "NA - Final result of malaria from blood smear test"
label variable hml32_07 "NA - Final result of malaria from blood smear test"
label variable hml32_08 "NA - Final result of malaria from blood smear test"
label variable hml32_09 "NA - Final result of malaria from blood smear test"
label variable hml32_10 "NA - Final result of malaria from blood smear test"
label variable hml32_11 "NA - Final result of malaria from blood smear test"
label variable hml32_12 "NA - Final result of malaria from blood smear test"
label variable hml32_13 "NA - Final result of malaria from blood smear test"
label variable hml32_14 "NA - Final result of malaria from blood smear test"
label variable hml32_15 "NA - Final result of malaria from blood smear test"
label variable hml32_16 "NA - Final result of malaria from blood smear test"
label variable hml32_17 "NA - Final result of malaria from blood smear test"
label variable hml32_18 "NA - Final result of malaria from blood smear test"
label variable hml32_19 "NA - Final result of malaria from blood smear test"
label variable hml32_20 "NA - Final result of malaria from blood smear test"
label variable hml32_21 "NA - Final result of malaria from blood smear test"
label variable hml32_22 "NA - Final result of malaria from blood smear test"
label variable hml32_23 "NA - Final result of malaria from blood smear test"
label variable hml32_24 "NA - Final result of malaria from blood smear test"
label variable hml32_25 "NA - Final result of malaria from blood smear test"
label variable hml32_26 "NA - Final result of malaria from blood smear test"
label variable hml32_27 "NA - Final result of malaria from blood smear test"
label variable hml32_28 "NA - Final result of malaria from blood smear test"
label variable hml32_29 "NA - Final result of malaria from blood smear test"
label variable hml32_30 "NA - Final result of malaria from blood smear test"
label variable hml32_31 "NA - Final result of malaria from blood smear test"
label variable hml32_32 "NA - Final result of malaria from blood smear test"
label variable hml32_33 "NA - Final result of malaria from blood smear test"
label variable hml32a_01 "NA - Presence of species: falciparum (Pf)"
label variable hml32a_02 "NA - Presence of species: falciparum (Pf)"
label variable hml32a_03 "NA - Presence of species: falciparum (Pf)"
label variable hml32a_04 "NA - Presence of species: falciparum (Pf)"
label variable hml32a_05 "NA - Presence of species: falciparum (Pf)"
label variable hml32a_06 "NA - Presence of species: falciparum (Pf)"
label variable hml32a_07 "NA - Presence of species: falciparum (Pf)"
label variable hml32a_08 "NA - Presence of species: falciparum (Pf)"
label variable hml32a_09 "NA - Presence of species: falciparum (Pf)"
label variable hml32a_10 "NA - Presence of species: falciparum (Pf)"
label variable hml32a_11 "NA - Presence of species: falciparum (Pf)"
label variable hml32a_12 "NA - Presence of species: falciparum (Pf)"
label variable hml32a_13 "NA - Presence of species: falciparum (Pf)"
label variable hml32a_14 "NA - Presence of species: falciparum (Pf)"
label variable hml32a_15 "NA - Presence of species: falciparum (Pf)"
label variable hml32a_16 "NA - Presence of species: falciparum (Pf)"
label variable hml32a_17 "NA - Presence of species: falciparum (Pf)"
label variable hml32a_18 "NA - Presence of species: falciparum (Pf)"
label variable hml32a_19 "NA - Presence of species: falciparum (Pf)"
label variable hml32a_20 "NA - Presence of species: falciparum (Pf)"
label variable hml32a_21 "NA - Presence of species: falciparum (Pf)"
label variable hml32a_22 "NA - Presence of species: falciparum (Pf)"
label variable hml32a_23 "NA - Presence of species: falciparum (Pf)"
label variable hml32a_24 "NA - Presence of species: falciparum (Pf)"
label variable hml32a_25 "NA - Presence of species: falciparum (Pf)"
label variable hml32a_26 "NA - Presence of species: falciparum (Pf)"
label variable hml32a_27 "NA - Presence of species: falciparum (Pf)"
label variable hml32a_28 "NA - Presence of species: falciparum (Pf)"
label variable hml32a_29 "NA - Presence of species: falciparum (Pf)"
label variable hml32a_30 "NA - Presence of species: falciparum (Pf)"
label variable hml32a_31 "NA - Presence of species: falciparum (Pf)"
label variable hml32a_32 "NA - Presence of species: falciparum (Pf)"
label variable hml32a_33 "NA - Presence of species: falciparum (Pf)"
label variable hml32b_01 "NA - Presence of species: malariae (Pm)"
label variable hml32b_02 "NA - Presence of species: malariae (Pm)"
label variable hml32b_03 "NA - Presence of species: malariae (Pm)"
label variable hml32b_04 "NA - Presence of species: malariae (Pm)"
label variable hml32b_05 "NA - Presence of species: malariae (Pm)"
label variable hml32b_06 "NA - Presence of species: malariae (Pm)"
label variable hml32b_07 "NA - Presence of species: malariae (Pm)"
label variable hml32b_08 "NA - Presence of species: malariae (Pm)"
label variable hml32b_09 "NA - Presence of species: malariae (Pm)"
label variable hml32b_10 "NA - Presence of species: malariae (Pm)"
label variable hml32b_11 "NA - Presence of species: malariae (Pm)"
label variable hml32b_12 "NA - Presence of species: malariae (Pm)"
label variable hml32b_13 "NA - Presence of species: malariae (Pm)"
label variable hml32b_14 "NA - Presence of species: malariae (Pm)"
label variable hml32b_15 "NA - Presence of species: malariae (Pm)"
label variable hml32b_16 "NA - Presence of species: malariae (Pm)"
label variable hml32b_17 "NA - Presence of species: malariae (Pm)"
label variable hml32b_18 "NA - Presence of species: malariae (Pm)"
label variable hml32b_19 "NA - Presence of species: malariae (Pm)"
label variable hml32b_20 "NA - Presence of species: malariae (Pm)"
label variable hml32b_21 "NA - Presence of species: malariae (Pm)"
label variable hml32b_22 "NA - Presence of species: malariae (Pm)"
label variable hml32b_23 "NA - Presence of species: malariae (Pm)"
label variable hml32b_24 "NA - Presence of species: malariae (Pm)"
label variable hml32b_25 "NA - Presence of species: malariae (Pm)"
label variable hml32b_26 "NA - Presence of species: malariae (Pm)"
label variable hml32b_27 "NA - Presence of species: malariae (Pm)"
label variable hml32b_28 "NA - Presence of species: malariae (Pm)"
label variable hml32b_29 "NA - Presence of species: malariae (Pm)"
label variable hml32b_30 "NA - Presence of species: malariae (Pm)"
label variable hml32b_31 "NA - Presence of species: malariae (Pm)"
label variable hml32b_32 "NA - Presence of species: malariae (Pm)"
label variable hml32b_33 "NA - Presence of species: malariae (Pm)"
label variable hml32c_01 "NA - Presence of species: ovale (Po)"
label variable hml32c_02 "NA - Presence of species: ovale (Po)"
label variable hml32c_03 "NA - Presence of species: ovale (Po)"
label variable hml32c_04 "NA - Presence of species: ovale (Po)"
label variable hml32c_05 "NA - Presence of species: ovale (Po)"
label variable hml32c_06 "NA - Presence of species: ovale (Po)"
label variable hml32c_07 "NA - Presence of species: ovale (Po)"
label variable hml32c_08 "NA - Presence of species: ovale (Po)"
label variable hml32c_09 "NA - Presence of species: ovale (Po)"
label variable hml32c_10 "NA - Presence of species: ovale (Po)"
label variable hml32c_11 "NA - Presence of species: ovale (Po)"
label variable hml32c_12 "NA - Presence of species: ovale (Po)"
label variable hml32c_13 "NA - Presence of species: ovale (Po)"
label variable hml32c_14 "NA - Presence of species: ovale (Po)"
label variable hml32c_15 "NA - Presence of species: ovale (Po)"
label variable hml32c_16 "NA - Presence of species: ovale (Po)"
label variable hml32c_17 "NA - Presence of species: ovale (Po)"
label variable hml32c_18 "NA - Presence of species: ovale (Po)"
label variable hml32c_19 "NA - Presence of species: ovale (Po)"
label variable hml32c_20 "NA - Presence of species: ovale (Po)"
label variable hml32c_21 "NA - Presence of species: ovale (Po)"
label variable hml32c_22 "NA - Presence of species: ovale (Po)"
label variable hml32c_23 "NA - Presence of species: ovale (Po)"
label variable hml32c_24 "NA - Presence of species: ovale (Po)"
label variable hml32c_25 "NA - Presence of species: ovale (Po)"
label variable hml32c_26 "NA - Presence of species: ovale (Po)"
label variable hml32c_27 "NA - Presence of species: ovale (Po)"
label variable hml32c_28 "NA - Presence of species: ovale (Po)"
label variable hml32c_29 "NA - Presence of species: ovale (Po)"
label variable hml32c_30 "NA - Presence of species: ovale (Po)"
label variable hml32c_31 "NA - Presence of species: ovale (Po)"
label variable hml32c_32 "NA - Presence of species: ovale (Po)"
label variable hml32c_33 "NA - Presence of species: ovale (Po)"
label variable hml32d_01 "NA - Presence of species: vivax (Pv)"
label variable hml32d_02 "NA - Presence of species: vivax (Pv)"
label variable hml32d_03 "NA - Presence of species: vivax (Pv)"
label variable hml32d_04 "NA - Presence of species: vivax (Pv)"
label variable hml32d_05 "NA - Presence of species: vivax (Pv)"
label variable hml32d_06 "NA - Presence of species: vivax (Pv)"
label variable hml32d_07 "NA - Presence of species: vivax (Pv)"
label variable hml32d_08 "NA - Presence of species: vivax (Pv)"
label variable hml32d_09 "NA - Presence of species: vivax (Pv)"
label variable hml32d_10 "NA - Presence of species: vivax (Pv)"
label variable hml32d_11 "NA - Presence of species: vivax (Pv)"
label variable hml32d_12 "NA - Presence of species: vivax (Pv)"
label variable hml32d_13 "NA - Presence of species: vivax (Pv)"
label variable hml32d_14 "NA - Presence of species: vivax (Pv)"
label variable hml32d_15 "NA - Presence of species: vivax (Pv)"
label variable hml32d_16 "NA - Presence of species: vivax (Pv)"
label variable hml32d_17 "NA - Presence of species: vivax (Pv)"
label variable hml32d_18 "NA - Presence of species: vivax (Pv)"
label variable hml32d_19 "NA - Presence of species: vivax (Pv)"
label variable hml32d_20 "NA - Presence of species: vivax (Pv)"
label variable hml32d_21 "NA - Presence of species: vivax (Pv)"
label variable hml32d_22 "NA - Presence of species: vivax (Pv)"
label variable hml32d_23 "NA - Presence of species: vivax (Pv)"
label variable hml32d_24 "NA - Presence of species: vivax (Pv)"
label variable hml32d_25 "NA - Presence of species: vivax (Pv)"
label variable hml32d_26 "NA - Presence of species: vivax (Pv)"
label variable hml32d_27 "NA - Presence of species: vivax (Pv)"
label variable hml32d_28 "NA - Presence of species: vivax (Pv)"
label variable hml32d_29 "NA - Presence of species: vivax (Pv)"
label variable hml32d_30 "NA - Presence of species: vivax (Pv)"
label variable hml32d_31 "NA - Presence of species: vivax (Pv)"
label variable hml32d_32 "NA - Presence of species: vivax (Pv)"
label variable hml32d_33 "NA - Presence of species: vivax (Pv)"
label variable hml32e_01 "NA - Presence of species: CS"
label variable hml32e_02 "NA - Presence of species: CS"
label variable hml32e_03 "NA - Presence of species: CS"
label variable hml32e_04 "NA - Presence of species: CS"
label variable hml32e_05 "NA - Presence of species: CS"
label variable hml32e_06 "NA - Presence of species: CS"
label variable hml32e_07 "NA - Presence of species: CS"
label variable hml32e_08 "NA - Presence of species: CS"
label variable hml32e_09 "NA - Presence of species: CS"
label variable hml32e_10 "NA - Presence of species: CS"
label variable hml32e_11 "NA - Presence of species: CS"
label variable hml32e_12 "NA - Presence of species: CS"
label variable hml32e_13 "NA - Presence of species: CS"
label variable hml32e_14 "NA - Presence of species: CS"
label variable hml32e_15 "NA - Presence of species: CS"
label variable hml32e_16 "NA - Presence of species: CS"
label variable hml32e_17 "NA - Presence of species: CS"
label variable hml32e_18 "NA - Presence of species: CS"
label variable hml32e_19 "NA - Presence of species: CS"
label variable hml32e_20 "NA - Presence of species: CS"
label variable hml32e_21 "NA - Presence of species: CS"
label variable hml32e_22 "NA - Presence of species: CS"
label variable hml32e_23 "NA - Presence of species: CS"
label variable hml32e_24 "NA - Presence of species: CS"
label variable hml32e_25 "NA - Presence of species: CS"
label variable hml32e_26 "NA - Presence of species: CS"
label variable hml32e_27 "NA - Presence of species: CS"
label variable hml32e_28 "NA - Presence of species: CS"
label variable hml32e_29 "NA - Presence of species: CS"
label variable hml32e_30 "NA - Presence of species: CS"
label variable hml32e_31 "NA - Presence of species: CS"
label variable hml32e_32 "NA - Presence of species: CS"
label variable hml32e_33 "NA - Presence of species: CS"
label variable hml32f_01 "NA - Presence of species: CS"
label variable hml32f_02 "NA - Presence of species: CS"
label variable hml32f_03 "NA - Presence of species: CS"
label variable hml32f_04 "NA - Presence of species: CS"
label variable hml32f_05 "NA - Presence of species: CS"
label variable hml32f_06 "NA - Presence of species: CS"
label variable hml32f_07 "NA - Presence of species: CS"
label variable hml32f_08 "NA - Presence of species: CS"
label variable hml32f_09 "NA - Presence of species: CS"
label variable hml32f_10 "NA - Presence of species: CS"
label variable hml32f_11 "NA - Presence of species: CS"
label variable hml32f_12 "NA - Presence of species: CS"
label variable hml32f_13 "NA - Presence of species: CS"
label variable hml32f_14 "NA - Presence of species: CS"
label variable hml32f_15 "NA - Presence of species: CS"
label variable hml32f_16 "NA - Presence of species: CS"
label variable hml32f_17 "NA - Presence of species: CS"
label variable hml32f_18 "NA - Presence of species: CS"
label variable hml32f_19 "NA - Presence of species: CS"
label variable hml32f_20 "NA - Presence of species: CS"
label variable hml32f_21 "NA - Presence of species: CS"
label variable hml32f_22 "NA - Presence of species: CS"
label variable hml32f_23 "NA - Presence of species: CS"
label variable hml32f_24 "NA - Presence of species: CS"
label variable hml32f_25 "NA - Presence of species: CS"
label variable hml32f_26 "NA - Presence of species: CS"
label variable hml32f_27 "NA - Presence of species: CS"
label variable hml32f_28 "NA - Presence of species: CS"
label variable hml32f_29 "NA - Presence of species: CS"
label variable hml32f_30 "NA - Presence of species: CS"
label variable hml32f_31 "NA - Presence of species: CS"
label variable hml32f_32 "NA - Presence of species: CS"
label variable hml32f_33 "NA - Presence of species: CS"
label variable hml32g_01 "NA - Presence of species: CS"
label variable hml32g_02 "NA - Presence of species: CS"
label variable hml32g_03 "NA - Presence of species: CS"
label variable hml32g_04 "NA - Presence of species: CS"
label variable hml32g_05 "NA - Presence of species: CS"
label variable hml32g_06 "NA - Presence of species: CS"
label variable hml32g_07 "NA - Presence of species: CS"
label variable hml32g_08 "NA - Presence of species: CS"
label variable hml32g_09 "NA - Presence of species: CS"
label variable hml32g_10 "NA - Presence of species: CS"
label variable hml32g_11 "NA - Presence of species: CS"
label variable hml32g_12 "NA - Presence of species: CS"
label variable hml32g_13 "NA - Presence of species: CS"
label variable hml32g_14 "NA - Presence of species: CS"
label variable hml32g_15 "NA - Presence of species: CS"
label variable hml32g_16 "NA - Presence of species: CS"
label variable hml32g_17 "NA - Presence of species: CS"
label variable hml32g_18 "NA - Presence of species: CS"
label variable hml32g_19 "NA - Presence of species: CS"
label variable hml32g_20 "NA - Presence of species: CS"
label variable hml32g_21 "NA - Presence of species: CS"
label variable hml32g_22 "NA - Presence of species: CS"
label variable hml32g_23 "NA - Presence of species: CS"
label variable hml32g_24 "NA - Presence of species: CS"
label variable hml32g_25 "NA - Presence of species: CS"
label variable hml32g_26 "NA - Presence of species: CS"
label variable hml32g_27 "NA - Presence of species: CS"
label variable hml32g_28 "NA - Presence of species: CS"
label variable hml32g_29 "NA - Presence of species: CS"
label variable hml32g_30 "NA - Presence of species: CS"
label variable hml32g_31 "NA - Presence of species: CS"
label variable hml32g_32 "NA - Presence of species: CS"
label variable hml32g_33 "NA - Presence of species: CS"
label variable hml33_01 "Result of malaria measurement"
label variable hml33_02 "Result of malaria measurement"
label variable hml33_03 "Result of malaria measurement"
label variable hml33_04 "Result of malaria measurement"
label variable hml33_05 "Result of malaria measurement"
label variable hml33_06 "Result of malaria measurement"
label variable hml33_07 "Result of malaria measurement"
label variable hml33_08 "Result of malaria measurement"
label variable hml33_09 "Result of malaria measurement"
label variable hml33_10 "Result of malaria measurement"
label variable hml33_11 "Result of malaria measurement"
label variable hml33_12 "Result of malaria measurement"
label variable hml33_13 "Result of malaria measurement"
label variable hml33_14 "Result of malaria measurement"
label variable hml33_15 "Result of malaria measurement"
label variable hml33_16 "Result of malaria measurement"
label variable hml33_17 "Result of malaria measurement"
label variable hml33_18 "Result of malaria measurement"
label variable hml33_19 "Result of malaria measurement"
label variable hml33_20 "Result of malaria measurement"
label variable hml33_21 "Result of malaria measurement"
label variable hml33_22 "Result of malaria measurement"
label variable hml33_23 "Result of malaria measurement"
label variable hml33_24 "Result of malaria measurement"
label variable hml33_25 "Result of malaria measurement"
label variable hml33_26 "Result of malaria measurement"
label variable hml33_27 "Result of malaria measurement"
label variable hml33_28 "Result of malaria measurement"
label variable hml33_29 "Result of malaria measurement"
label variable hml33_30 "Result of malaria measurement"
label variable hml33_31 "Result of malaria measurement"
label variable hml33_32 "Result of malaria measurement"
label variable hml33_33 "Result of malaria measurement"
label variable hml34_01 "NA - Bar code for blood smear sample"
label variable hml34_02 "NA - Bar code for blood smear sample"
label variable hml34_03 "NA - Bar code for blood smear sample"
label variable hml34_04 "NA - Bar code for blood smear sample"
label variable hml34_05 "NA - Bar code for blood smear sample"
label variable hml34_06 "NA - Bar code for blood smear sample"
label variable hml34_07 "NA - Bar code for blood smear sample"
label variable hml34_08 "NA - Bar code for blood smear sample"
label variable hml34_09 "NA - Bar code for blood smear sample"
label variable hml34_10 "NA - Bar code for blood smear sample"
label variable hml34_11 "NA - Bar code for blood smear sample"
label variable hml34_12 "NA - Bar code for blood smear sample"
label variable hml34_13 "NA - Bar code for blood smear sample"
label variable hml34_14 "NA - Bar code for blood smear sample"
label variable hml34_15 "NA - Bar code for blood smear sample"
label variable hml34_16 "NA - Bar code for blood smear sample"
label variable hml34_17 "NA - Bar code for blood smear sample"
label variable hml34_18 "NA - Bar code for blood smear sample"
label variable hml34_19 "NA - Bar code for blood smear sample"
label variable hml34_20 "NA - Bar code for blood smear sample"
label variable hml34_21 "NA - Bar code for blood smear sample"
label variable hml34_22 "NA - Bar code for blood smear sample"
label variable hml34_23 "NA - Bar code for blood smear sample"
label variable hml34_24 "NA - Bar code for blood smear sample"
label variable hml34_25 "NA - Bar code for blood smear sample"
label variable hml34_26 "NA - Bar code for blood smear sample"
label variable hml34_27 "NA - Bar code for blood smear sample"
label variable hml34_28 "NA - Bar code for blood smear sample"
label variable hml34_29 "NA - Bar code for blood smear sample"
label variable hml34_30 "NA - Bar code for blood smear sample"
label variable hml34_31 "NA - Bar code for blood smear sample"
label variable hml34_32 "NA - Bar code for blood smear sample"
label variable hml34_33 "NA - Bar code for blood smear sample"
label variable hml35_01 "Result of malaria rapid test"
label variable hml35_02 "Result of malaria rapid test"
label variable hml35_03 "Result of malaria rapid test"
label variable hml35_04 "Result of malaria rapid test"
label variable hml35_05 "Result of malaria rapid test"
label variable hml35_06 "Result of malaria rapid test"
label variable hml35_07 "Result of malaria rapid test"
label variable hml35_08 "Result of malaria rapid test"
label variable hml35_09 "Result of malaria rapid test"
label variable hml35_10 "Result of malaria rapid test"
label variable hml35_11 "Result of malaria rapid test"
label variable hml35_12 "Result of malaria rapid test"
label variable hml35_13 "Result of malaria rapid test"
label variable hml35_14 "Result of malaria rapid test"
label variable hml35_15 "Result of malaria rapid test"
label variable hml35_16 "Result of malaria rapid test"
label variable hml35_17 "Result of malaria rapid test"
label variable hml35_18 "Result of malaria rapid test"
label variable hml35_19 "Result of malaria rapid test"
label variable hml35_20 "Result of malaria rapid test"
label variable hml35_21 "Result of malaria rapid test"
label variable hml35_22 "Result of malaria rapid test"
label variable hml35_23 "Result of malaria rapid test"
label variable hml35_24 "Result of malaria rapid test"
label variable hml35_25 "Result of malaria rapid test"
label variable hml35_26 "Result of malaria rapid test"
label variable hml35_27 "Result of malaria rapid test"
label variable hml35_28 "Result of malaria rapid test"
label variable hml35_29 "Result of malaria rapid test"
label variable hml35_30 "Result of malaria rapid test"
label variable hml35_31 "Result of malaria rapid test"
label variable hml35_32 "Result of malaria rapid test"
label variable hml35_33 "Result of malaria rapid test"
label variable hml36_01 "Fieldworker measurer code for malaria"
label variable hml36_02 "Fieldworker measurer code for malaria"
label variable hml36_03 "Fieldworker measurer code for malaria"
label variable hml36_04 "Fieldworker measurer code for malaria"
label variable hml36_05 "Fieldworker measurer code for malaria"
label variable hml36_06 "Fieldworker measurer code for malaria"
label variable hml36_07 "Fieldworker measurer code for malaria"
label variable hml36_08 "Fieldworker measurer code for malaria"
label variable hml36_09 "Fieldworker measurer code for malaria"
label variable hml36_10 "Fieldworker measurer code for malaria"
label variable hml36_11 "Fieldworker measurer code for malaria"
label variable hml36_12 "Fieldworker measurer code for malaria"
label variable hml36_13 "Fieldworker measurer code for malaria"
label variable hml36_14 "Fieldworker measurer code for malaria"
label variable hml36_15 "Fieldworker measurer code for malaria"
label variable hml36_16 "Fieldworker measurer code for malaria"
label variable hml36_17 "Fieldworker measurer code for malaria"
label variable hml36_18 "Fieldworker measurer code for malaria"
label variable hml36_19 "Fieldworker measurer code for malaria"
label variable hml36_20 "Fieldworker measurer code for malaria"
label variable hml36_21 "Fieldworker measurer code for malaria"
label variable hml36_22 "Fieldworker measurer code for malaria"
label variable hml36_23 "Fieldworker measurer code for malaria"
label variable hml36_24 "Fieldworker measurer code for malaria"
label variable hml36_25 "Fieldworker measurer code for malaria"
label variable hml36_26 "Fieldworker measurer code for malaria"
label variable hml36_27 "Fieldworker measurer code for malaria"
label variable hml36_28 "Fieldworker measurer code for malaria"
label variable hml36_29 "Fieldworker measurer code for malaria"
label variable hml36_30 "Fieldworker measurer code for malaria"
label variable hml36_31 "Fieldworker measurer code for malaria"
label variable hml36_32 "Fieldworker measurer code for malaria"
label variable hml36_33 "Fieldworker measurer code for malaria"
label variable sb114_01 "Malaria rapid test result (RDT)"
label variable sb114_02 "Malaria rapid test result (RDT)"
label variable sb114_03 "Malaria rapid test result (RDT)"
label variable sb114_04 "Malaria rapid test result (RDT)"
label variable sb114_05 "Malaria rapid test result (RDT)"
label variable sb114_06 "Malaria rapid test result (RDT)"
label variable sb114_07 "Malaria rapid test result (RDT)"
label variable sb114_08 "Malaria rapid test result (RDT)"
label variable sb114_09 "Malaria rapid test result (RDT)"
label variable sb114_10 "Malaria rapid test result (RDT)"
label variable sb114_11 "Malaria rapid test result (RDT)"
label variable sb114_12 "Malaria rapid test result (RDT)"
label variable sb114_13 "Malaria rapid test result (RDT)"
label variable sb114_14 "Malaria rapid test result (RDT)"
label variable sb114_15 "Malaria rapid test result (RDT)"
label variable sb114_16 "Malaria rapid test result (RDT)"
label variable sb114_17 "Malaria rapid test result (RDT)"
label variable sb114_18 "Malaria rapid test result (RDT)"
label variable sb114_19 "Malaria rapid test result (RDT)"
label variable sb114_20 "Malaria rapid test result (RDT)"
label variable sb114_21 "Malaria rapid test result (RDT)"
label variable sb114_22 "Malaria rapid test result (RDT)"
label variable sb114_23 "Malaria rapid test result (RDT)"
label variable sb114_24 "Malaria rapid test result (RDT)"
label variable sb114_25 "Malaria rapid test result (RDT)"
label variable sb114_26 "Malaria rapid test result (RDT)"
label variable sb114_27 "Malaria rapid test result (RDT)"
label variable sb114_28 "Malaria rapid test result (RDT)"
label variable sb114_29 "Malaria rapid test result (RDT)"
label variable sb114_30 "Malaria rapid test result (RDT)"
label variable sb114_31 "Malaria rapid test result (RDT)"
label variable sb114_32 "Malaria rapid test result (RDT)"
label variable sb114_33 "Malaria rapid test result (RDT)"
label variable sb115a_01 "Child suffers: Prostration"
label variable sb115a_02 "Child suffers: Prostration"
label variable sb115a_03 "Child suffers: Prostration"
label variable sb115a_04 "Child suffers: Prostration"
label variable sb115a_05 "Child suffers: Prostration"
label variable sb115a_06 "Child suffers: Prostration"
label variable sb115a_07 "Child suffers: Prostration"
label variable sb115a_08 "Child suffers: Prostration"
label variable sb115a_09 "Child suffers: Prostration"
label variable sb115a_10 "Child suffers: Prostration"
label variable sb115a_11 "Child suffers: Prostration"
label variable sb115a_12 "Child suffers: Prostration"
label variable sb115a_13 "Child suffers: Prostration"
label variable sb115a_14 "Child suffers: Prostration"
label variable sb115a_15 "Child suffers: Prostration"
label variable sb115a_16 "Child suffers: Prostration"
label variable sb115a_17 "Child suffers: Prostration"
label variable sb115a_18 "Child suffers: Prostration"
label variable sb115a_19 "Child suffers: Prostration"
label variable sb115a_20 "Child suffers: Prostration"
label variable sb115a_21 "Child suffers: Prostration"
label variable sb115a_22 "Child suffers: Prostration"
label variable sb115a_23 "Child suffers: Prostration"
label variable sb115a_24 "Child suffers: Prostration"
label variable sb115a_25 "Child suffers: Prostration"
label variable sb115a_26 "Child suffers: Prostration"
label variable sb115a_27 "Child suffers: Prostration"
label variable sb115a_28 "Child suffers: Prostration"
label variable sb115a_29 "Child suffers: Prostration"
label variable sb115a_30 "Child suffers: Prostration"
label variable sb115a_31 "Child suffers: Prostration"
label variable sb115a_32 "Child suffers: Prostration"
label variable sb115a_33 "Child suffers: Prostration"
label variable sb115b_01 "Child suffers: Heart problems"
label variable sb115b_02 "Child suffers: Heart problems"
label variable sb115b_03 "Child suffers: Heart problems"
label variable sb115b_04 "Child suffers: Heart problems"
label variable sb115b_05 "Child suffers: Heart problems"
label variable sb115b_06 "Child suffers: Heart problems"
label variable sb115b_07 "Child suffers: Heart problems"
label variable sb115b_08 "Child suffers: Heart problems"
label variable sb115b_09 "Child suffers: Heart problems"
label variable sb115b_10 "Child suffers: Heart problems"
label variable sb115b_11 "Child suffers: Heart problems"
label variable sb115b_12 "Child suffers: Heart problems"
label variable sb115b_13 "Child suffers: Heart problems"
label variable sb115b_14 "Child suffers: Heart problems"
label variable sb115b_15 "Child suffers: Heart problems"
label variable sb115b_16 "Child suffers: Heart problems"
label variable sb115b_17 "Child suffers: Heart problems"
label variable sb115b_18 "Child suffers: Heart problems"
label variable sb115b_19 "Child suffers: Heart problems"
label variable sb115b_20 "Child suffers: Heart problems"
label variable sb115b_21 "Child suffers: Heart problems"
label variable sb115b_22 "Child suffers: Heart problems"
label variable sb115b_23 "Child suffers: Heart problems"
label variable sb115b_24 "Child suffers: Heart problems"
label variable sb115b_25 "Child suffers: Heart problems"
label variable sb115b_26 "Child suffers: Heart problems"
label variable sb115b_27 "Child suffers: Heart problems"
label variable sb115b_28 "Child suffers: Heart problems"
label variable sb115b_29 "Child suffers: Heart problems"
label variable sb115b_30 "Child suffers: Heart problems"
label variable sb115b_31 "Child suffers: Heart problems"
label variable sb115b_32 "Child suffers: Heart problems"
label variable sb115b_33 "Child suffers: Heart problems"
label variable sb115c_01 "Child suffers: Loss of consciousness"
label variable sb115c_02 "Child suffers: Loss of consciousness"
label variable sb115c_03 "Child suffers: Loss of consciousness"
label variable sb115c_04 "Child suffers: Loss of consciousness"
label variable sb115c_05 "Child suffers: Loss of consciousness"
label variable sb115c_06 "Child suffers: Loss of consciousness"
label variable sb115c_07 "Child suffers: Loss of consciousness"
label variable sb115c_08 "Child suffers: Loss of consciousness"
label variable sb115c_09 "Child suffers: Loss of consciousness"
label variable sb115c_10 "Child suffers: Loss of consciousness"
label variable sb115c_11 "Child suffers: Loss of consciousness"
label variable sb115c_12 "Child suffers: Loss of consciousness"
label variable sb115c_13 "Child suffers: Loss of consciousness"
label variable sb115c_14 "Child suffers: Loss of consciousness"
label variable sb115c_15 "Child suffers: Loss of consciousness"
label variable sb115c_16 "Child suffers: Loss of consciousness"
label variable sb115c_17 "Child suffers: Loss of consciousness"
label variable sb115c_18 "Child suffers: Loss of consciousness"
label variable sb115c_19 "Child suffers: Loss of consciousness"
label variable sb115c_20 "Child suffers: Loss of consciousness"
label variable sb115c_21 "Child suffers: Loss of consciousness"
label variable sb115c_22 "Child suffers: Loss of consciousness"
label variable sb115c_23 "Child suffers: Loss of consciousness"
label variable sb115c_24 "Child suffers: Loss of consciousness"
label variable sb115c_25 "Child suffers: Loss of consciousness"
label variable sb115c_26 "Child suffers: Loss of consciousness"
label variable sb115c_27 "Child suffers: Loss of consciousness"
label variable sb115c_28 "Child suffers: Loss of consciousness"
label variable sb115c_29 "Child suffers: Loss of consciousness"
label variable sb115c_30 "Child suffers: Loss of consciousness"
label variable sb115c_31 "Child suffers: Loss of consciousness"
label variable sb115c_32 "Child suffers: Loss of consciousness"
label variable sb115c_33 "Child suffers: Loss of consciousness"
label variable sb115d_01 "Child suffers: Difficult/rapid breathing"
label variable sb115d_02 "Child suffers: Difficult/rapid breathing"
label variable sb115d_03 "Child suffers: Difficult/rapid breathing"
label variable sb115d_04 "Child suffers: Difficult/rapid breathing"
label variable sb115d_05 "Child suffers: Difficult/rapid breathing"
label variable sb115d_06 "Child suffers: Difficult/rapid breathing"
label variable sb115d_07 "Child suffers: Difficult/rapid breathing"
label variable sb115d_08 "Child suffers: Difficult/rapid breathing"
label variable sb115d_09 "Child suffers: Difficult/rapid breathing"
label variable sb115d_10 "Child suffers: Difficult/rapid breathing"
label variable sb115d_11 "Child suffers: Difficult/rapid breathing"
label variable sb115d_12 "Child suffers: Difficult/rapid breathing"
label variable sb115d_13 "Child suffers: Difficult/rapid breathing"
label variable sb115d_14 "Child suffers: Difficult/rapid breathing"
label variable sb115d_15 "Child suffers: Difficult/rapid breathing"
label variable sb115d_16 "Child suffers: Difficult/rapid breathing"
label variable sb115d_17 "Child suffers: Difficult/rapid breathing"
label variable sb115d_18 "Child suffers: Difficult/rapid breathing"
label variable sb115d_19 "Child suffers: Difficult/rapid breathing"
label variable sb115d_20 "Child suffers: Difficult/rapid breathing"
label variable sb115d_21 "Child suffers: Difficult/rapid breathing"
label variable sb115d_22 "Child suffers: Difficult/rapid breathing"
label variable sb115d_23 "Child suffers: Difficult/rapid breathing"
label variable sb115d_24 "Child suffers: Difficult/rapid breathing"
label variable sb115d_25 "Child suffers: Difficult/rapid breathing"
label variable sb115d_26 "Child suffers: Difficult/rapid breathing"
label variable sb115d_27 "Child suffers: Difficult/rapid breathing"
label variable sb115d_28 "Child suffers: Difficult/rapid breathing"
label variable sb115d_29 "Child suffers: Difficult/rapid breathing"
label variable sb115d_30 "Child suffers: Difficult/rapid breathing"
label variable sb115d_31 "Child suffers: Difficult/rapid breathing"
label variable sb115d_32 "Child suffers: Difficult/rapid breathing"
label variable sb115d_33 "Child suffers: Difficult/rapid breathing"
label variable sb115e_01 "Child suffers: Convulsions"
label variable sb115e_02 "Child suffers: Convulsions"
label variable sb115e_03 "Child suffers: Convulsions"
label variable sb115e_04 "Child suffers: Convulsions"
label variable sb115e_05 "Child suffers: Convulsions"
label variable sb115e_06 "Child suffers: Convulsions"
label variable sb115e_07 "Child suffers: Convulsions"
label variable sb115e_08 "Child suffers: Convulsions"
label variable sb115e_09 "Child suffers: Convulsions"
label variable sb115e_10 "Child suffers: Convulsions"
label variable sb115e_11 "Child suffers: Convulsions"
label variable sb115e_12 "Child suffers: Convulsions"
label variable sb115e_13 "Child suffers: Convulsions"
label variable sb115e_14 "Child suffers: Convulsions"
label variable sb115e_15 "Child suffers: Convulsions"
label variable sb115e_16 "Child suffers: Convulsions"
label variable sb115e_17 "Child suffers: Convulsions"
label variable sb115e_18 "Child suffers: Convulsions"
label variable sb115e_19 "Child suffers: Convulsions"
label variable sb115e_20 "Child suffers: Convulsions"
label variable sb115e_21 "Child suffers: Convulsions"
label variable sb115e_22 "Child suffers: Convulsions"
label variable sb115e_23 "Child suffers: Convulsions"
label variable sb115e_24 "Child suffers: Convulsions"
label variable sb115e_25 "Child suffers: Convulsions"
label variable sb115e_26 "Child suffers: Convulsions"
label variable sb115e_27 "Child suffers: Convulsions"
label variable sb115e_28 "Child suffers: Convulsions"
label variable sb115e_29 "Child suffers: Convulsions"
label variable sb115e_30 "Child suffers: Convulsions"
label variable sb115e_31 "Child suffers: Convulsions"
label variable sb115e_32 "Child suffers: Convulsions"
label variable sb115e_33 "Child suffers: Convulsions"
label variable sb115f_01 "Child suffers: Abnormal bleeding"
label variable sb115f_02 "Child suffers: Abnormal bleeding"
label variable sb115f_03 "Child suffers: Abnormal bleeding"
label variable sb115f_04 "Child suffers: Abnormal bleeding"
label variable sb115f_05 "Child suffers: Abnormal bleeding"
label variable sb115f_06 "Child suffers: Abnormal bleeding"
label variable sb115f_07 "Child suffers: Abnormal bleeding"
label variable sb115f_08 "Child suffers: Abnormal bleeding"
label variable sb115f_09 "Child suffers: Abnormal bleeding"
label variable sb115f_10 "Child suffers: Abnormal bleeding"
label variable sb115f_11 "Child suffers: Abnormal bleeding"
label variable sb115f_12 "Child suffers: Abnormal bleeding"
label variable sb115f_13 "Child suffers: Abnormal bleeding"
label variable sb115f_14 "Child suffers: Abnormal bleeding"
label variable sb115f_15 "Child suffers: Abnormal bleeding"
label variable sb115f_16 "Child suffers: Abnormal bleeding"
label variable sb115f_17 "Child suffers: Abnormal bleeding"
label variable sb115f_18 "Child suffers: Abnormal bleeding"
label variable sb115f_19 "Child suffers: Abnormal bleeding"
label variable sb115f_20 "Child suffers: Abnormal bleeding"
label variable sb115f_21 "Child suffers: Abnormal bleeding"
label variable sb115f_22 "Child suffers: Abnormal bleeding"
label variable sb115f_23 "Child suffers: Abnormal bleeding"
label variable sb115f_24 "Child suffers: Abnormal bleeding"
label variable sb115f_25 "Child suffers: Abnormal bleeding"
label variable sb115f_26 "Child suffers: Abnormal bleeding"
label variable sb115f_27 "Child suffers: Abnormal bleeding"
label variable sb115f_28 "Child suffers: Abnormal bleeding"
label variable sb115f_29 "Child suffers: Abnormal bleeding"
label variable sb115f_30 "Child suffers: Abnormal bleeding"
label variable sb115f_31 "Child suffers: Abnormal bleeding"
label variable sb115f_32 "Child suffers: Abnormal bleeding"
label variable sb115f_33 "Child suffers: Abnormal bleeding"
label variable sb115g_01 "Child suffers: Jaundice"
label variable sb115g_02 "Child suffers: Jaundice"
label variable sb115g_03 "Child suffers: Jaundice"
label variable sb115g_04 "Child suffers: Jaundice"
label variable sb115g_05 "Child suffers: Jaundice"
label variable sb115g_06 "Child suffers: Jaundice"
label variable sb115g_07 "Child suffers: Jaundice"
label variable sb115g_08 "Child suffers: Jaundice"
label variable sb115g_09 "Child suffers: Jaundice"
label variable sb115g_10 "Child suffers: Jaundice"
label variable sb115g_11 "Child suffers: Jaundice"
label variable sb115g_12 "Child suffers: Jaundice"
label variable sb115g_13 "Child suffers: Jaundice"
label variable sb115g_14 "Child suffers: Jaundice"
label variable sb115g_15 "Child suffers: Jaundice"
label variable sb115g_16 "Child suffers: Jaundice"
label variable sb115g_17 "Child suffers: Jaundice"
label variable sb115g_18 "Child suffers: Jaundice"
label variable sb115g_19 "Child suffers: Jaundice"
label variable sb115g_20 "Child suffers: Jaundice"
label variable sb115g_21 "Child suffers: Jaundice"
label variable sb115g_22 "Child suffers: Jaundice"
label variable sb115g_23 "Child suffers: Jaundice"
label variable sb115g_24 "Child suffers: Jaundice"
label variable sb115g_25 "Child suffers: Jaundice"
label variable sb115g_26 "Child suffers: Jaundice"
label variable sb115g_27 "Child suffers: Jaundice"
label variable sb115g_28 "Child suffers: Jaundice"
label variable sb115g_29 "Child suffers: Jaundice"
label variable sb115g_30 "Child suffers: Jaundice"
label variable sb115g_31 "Child suffers: Jaundice"
label variable sb115g_32 "Child suffers: Jaundice"
label variable sb115g_33 "Child suffers: Jaundice"
label variable sb115h_01 "Child suffers: Dark urines"
label variable sb115h_02 "Child suffers: Dark urines"
label variable sb115h_03 "Child suffers: Dark urines"
label variable sb115h_04 "Child suffers: Dark urines"
label variable sb115h_05 "Child suffers: Dark urines"
label variable sb115h_06 "Child suffers: Dark urines"
label variable sb115h_07 "Child suffers: Dark urines"
label variable sb115h_08 "Child suffers: Dark urines"
label variable sb115h_09 "Child suffers: Dark urines"
label variable sb115h_10 "Child suffers: Dark urines"
label variable sb115h_11 "Child suffers: Dark urines"
label variable sb115h_12 "Child suffers: Dark urines"
label variable sb115h_13 "Child suffers: Dark urines"
label variable sb115h_14 "Child suffers: Dark urines"
label variable sb115h_15 "Child suffers: Dark urines"
label variable sb115h_16 "Child suffers: Dark urines"
label variable sb115h_17 "Child suffers: Dark urines"
label variable sb115h_18 "Child suffers: Dark urines"
label variable sb115h_19 "Child suffers: Dark urines"
label variable sb115h_20 "Child suffers: Dark urines"
label variable sb115h_21 "Child suffers: Dark urines"
label variable sb115h_22 "Child suffers: Dark urines"
label variable sb115h_23 "Child suffers: Dark urines"
label variable sb115h_24 "Child suffers: Dark urines"
label variable sb115h_25 "Child suffers: Dark urines"
label variable sb115h_26 "Child suffers: Dark urines"
label variable sb115h_27 "Child suffers: Dark urines"
label variable sb115h_28 "Child suffers: Dark urines"
label variable sb115h_29 "Child suffers: Dark urines"
label variable sb115h_30 "Child suffers: Dark urines"
label variable sb115h_31 "Child suffers: Dark urines"
label variable sb115h_32 "Child suffers: Dark urines"
label variable sb115h_33 "Child suffers: Dark urines"
label variable sb117_01 "Anemia level"
label variable sb117_02 "Anemia level"
label variable sb117_03 "Anemia level"
label variable sb117_04 "Anemia level"
label variable sb117_05 "Anemia level"
label variable sb117_06 "Anemia level"
label variable sb117_07 "Anemia level"
label variable sb117_08 "Anemia level"
label variable sb117_09 "Anemia level"
label variable sb117_10 "Anemia level"
label variable sb117_11 "Anemia level"
label variable sb117_12 "Anemia level"
label variable sb117_13 "Anemia level"
label variable sb117_14 "Anemia level"
label variable sb117_15 "Anemia level"
label variable sb117_16 "Anemia level"
label variable sb117_17 "Anemia level"
label variable sb117_18 "Anemia level"
label variable sb117_19 "Anemia level"
label variable sb117_20 "Anemia level"
label variable sb117_21 "Anemia level"
label variable sb117_22 "Anemia level"
label variable sb117_23 "Anemia level"
label variable sb117_24 "Anemia level"
label variable sb117_25 "Anemia level"
label variable sb117_26 "Anemia level"
label variable sb117_27 "Anemia level"
label variable sb117_28 "Anemia level"
label variable sb117_29 "Anemia level"
label variable sb117_30 "Anemia level"
label variable sb117_31 "Anemia level"
label variable sb117_32 "Anemia level"
label variable sb117_33 "Anemia level"
label variable sb119_01 "Taking ACT given by a doctor/health center to treat the malaria"
label variable sb119_02 "Taking ACT given by a doctor/health center to treat the malaria"
label variable sb119_03 "Taking ACT given by a doctor/health center to treat the malaria"
label variable sb119_04 "Taking ACT given by a doctor/health center to treat the malaria"
label variable sb119_05 "Taking ACT given by a doctor/health center to treat the malaria"
label variable sb119_06 "Taking ACT given by a doctor/health center to treat the malaria"
label variable sb119_07 "Taking ACT given by a doctor/health center to treat the malaria"
label variable sb119_08 "Taking ACT given by a doctor/health center to treat the malaria"
label variable sb119_09 "Taking ACT given by a doctor/health center to treat the malaria"
label variable sb119_10 "Taking ACT given by a doctor/health center to treat the malaria"
label variable sb119_11 "Taking ACT given by a doctor/health center to treat the malaria"
label variable sb119_12 "Taking ACT given by a doctor/health center to treat the malaria"
label variable sb119_13 "Taking ACT given by a doctor/health center to treat the malaria"
label variable sb119_14 "Taking ACT given by a doctor/health center to treat the malaria"
label variable sb119_15 "Taking ACT given by a doctor/health center to treat the malaria"
label variable sb119_16 "Taking ACT given by a doctor/health center to treat the malaria"
label variable sb119_17 "Taking ACT given by a doctor/health center to treat the malaria"
label variable sb119_18 "Taking ACT given by a doctor/health center to treat the malaria"
label variable sb119_19 "Taking ACT given by a doctor/health center to treat the malaria"
label variable sb119_20 "Taking ACT given by a doctor/health center to treat the malaria"
label variable sb119_21 "Taking ACT given by a doctor/health center to treat the malaria"
label variable sb119_22 "Taking ACT given by a doctor/health center to treat the malaria"
label variable sb119_23 "Taking ACT given by a doctor/health center to treat the malaria"
label variable sb119_24 "Taking ACT given by a doctor/health center to treat the malaria"
label variable sb119_25 "Taking ACT given by a doctor/health center to treat the malaria"
label variable sb119_26 "Taking ACT given by a doctor/health center to treat the malaria"
label variable sb119_27 "Taking ACT given by a doctor/health center to treat the malaria"
label variable sb119_28 "Taking ACT given by a doctor/health center to treat the malaria"
label variable sb119_29 "Taking ACT given by a doctor/health center to treat the malaria"
label variable sb119_30 "Taking ACT given by a doctor/health center to treat the malaria"
label variable sb119_31 "Taking ACT given by a doctor/health center to treat the malaria"
label variable sb119_32 "Taking ACT given by a doctor/health center to treat the malaria"
label variable sb119_33 "Taking ACT given by a doctor/health center to treat the malaria"
label variable sb122_01 "Accepted medicine for malaria treatment"
label variable sb122_02 "Accepted medicine for malaria treatment"
label variable sb122_03 "Accepted medicine for malaria treatment"
label variable sb122_04 "Accepted medicine for malaria treatment"
label variable sb122_05 "Accepted medicine for malaria treatment"
label variable sb122_06 "Accepted medicine for malaria treatment"
label variable sb122_07 "Accepted medicine for malaria treatment"
label variable sb122_08 "Accepted medicine for malaria treatment"
label variable sb122_09 "Accepted medicine for malaria treatment"
label variable sb122_10 "Accepted medicine for malaria treatment"
label variable sb122_11 "Accepted medicine for malaria treatment"
label variable sb122_12 "Accepted medicine for malaria treatment"
label variable sb122_13 "Accepted medicine for malaria treatment"
label variable sb122_14 "Accepted medicine for malaria treatment"
label variable sb122_15 "Accepted medicine for malaria treatment"
label variable sb122_16 "Accepted medicine for malaria treatment"
label variable sb122_17 "Accepted medicine for malaria treatment"
label variable sb122_18 "Accepted medicine for malaria treatment"
label variable sb122_19 "Accepted medicine for malaria treatment"
label variable sb122_20 "Accepted medicine for malaria treatment"
label variable sb122_21 "Accepted medicine for malaria treatment"
label variable sb122_22 "Accepted medicine for malaria treatment"
label variable sb122_23 "Accepted medicine for malaria treatment"
label variable sb122_24 "Accepted medicine for malaria treatment"
label variable sb122_25 "Accepted medicine for malaria treatment"
label variable sb122_26 "Accepted medicine for malaria treatment"
label variable sb122_27 "Accepted medicine for malaria treatment"
label variable sb122_28 "Accepted medicine for malaria treatment"
label variable sb122_29 "Accepted medicine for malaria treatment"
label variable sb122_30 "Accepted medicine for malaria treatment"
label variable sb122_31 "Accepted medicine for malaria treatment"
label variable sb122_32 "Accepted medicine for malaria treatment"
label variable sb122_33 "Accepted medicine for malaria treatment"
label variable sb123_01 "Fieldworker number for malaria medicine"
label variable sb123_02 "Fieldworker number for malaria medicine"
label variable sb123_03 "Fieldworker number for malaria medicine"
label variable sb123_04 "Fieldworker number for malaria medicine"
label variable sb123_05 "Fieldworker number for malaria medicine"
label variable sb123_06 "Fieldworker number for malaria medicine"
label variable sb123_07 "Fieldworker number for malaria medicine"
label variable sb123_08 "Fieldworker number for malaria medicine"
label variable sb123_09 "Fieldworker number for malaria medicine"
label variable sb123_10 "Fieldworker number for malaria medicine"
label variable sb123_11 "Fieldworker number for malaria medicine"
label variable sb123_12 "Fieldworker number for malaria medicine"
label variable sb123_13 "Fieldworker number for malaria medicine"
label variable sb123_14 "Fieldworker number for malaria medicine"
label variable sb123_15 "Fieldworker number for malaria medicine"
label variable sb123_16 "Fieldworker number for malaria medicine"
label variable sb123_17 "Fieldworker number for malaria medicine"
label variable sb123_18 "Fieldworker number for malaria medicine"
label variable sb123_19 "Fieldworker number for malaria medicine"
label variable sb123_20 "Fieldworker number for malaria medicine"
label variable sb123_21 "Fieldworker number for malaria medicine"
label variable sb123_22 "Fieldworker number for malaria medicine"
label variable sb123_23 "Fieldworker number for malaria medicine"
label variable sb123_24 "Fieldworker number for malaria medicine"
label variable sb123_25 "Fieldworker number for malaria medicine"
label variable sb123_26 "Fieldworker number for malaria medicine"
label variable sb123_27 "Fieldworker number for malaria medicine"
label variable sb123_28 "Fieldworker number for malaria medicine"
label variable sb123_29 "Fieldworker number for malaria medicine"
label variable sb123_30 "Fieldworker number for malaria medicine"
label variable sb123_31 "Fieldworker number for malaria medicine"
label variable sb123_32 "Fieldworker number for malaria medicine"
label variable sb123_33 "Fieldworker number for malaria medicine"
label variable sb126_01 "Anemia level for children with malaria and symptoms"
label variable sb126_02 "Anemia level for children with malaria and symptoms"
label variable sb126_03 "Anemia level for children with malaria and symptoms"
label variable sb126_04 "Anemia level for children with malaria and symptoms"
label variable sb126_05 "Anemia level for children with malaria and symptoms"
label variable sb126_06 "Anemia level for children with malaria and symptoms"
label variable sb126_07 "Anemia level for children with malaria and symptoms"
label variable sb126_08 "Anemia level for children with malaria and symptoms"
label variable sb126_09 "Anemia level for children with malaria and symptoms"
label variable sb126_10 "Anemia level for children with malaria and symptoms"
label variable sb126_11 "Anemia level for children with malaria and symptoms"
label variable sb126_12 "Anemia level for children with malaria and symptoms"
label variable sb126_13 "Anemia level for children with malaria and symptoms"
label variable sb126_14 "Anemia level for children with malaria and symptoms"
label variable sb126_15 "Anemia level for children with malaria and symptoms"
label variable sb126_16 "Anemia level for children with malaria and symptoms"
label variable sb126_17 "Anemia level for children with malaria and symptoms"
label variable sb126_18 "Anemia level for children with malaria and symptoms"
label variable sb126_19 "Anemia level for children with malaria and symptoms"
label variable sb126_20 "Anemia level for children with malaria and symptoms"
label variable sb126_21 "Anemia level for children with malaria and symptoms"
label variable sb126_22 "Anemia level for children with malaria and symptoms"
label variable sb126_23 "Anemia level for children with malaria and symptoms"
label variable sb126_24 "Anemia level for children with malaria and symptoms"
label variable sb126_25 "Anemia level for children with malaria and symptoms"
label variable sb126_26 "Anemia level for children with malaria and symptoms"
label variable sb126_27 "Anemia level for children with malaria and symptoms"
label variable sb126_28 "Anemia level for children with malaria and symptoms"
label variable sb126_29 "Anemia level for children with malaria and symptoms"
label variable sb126_30 "Anemia level for children with malaria and symptoms"
label variable sb126_31 "Anemia level for children with malaria and symptoms"
label variable sb126_32 "Anemia level for children with malaria and symptoms"
label variable sb126_33 "Anemia level for children with malaria and symptoms"
label variable sb128d_01 "Date measured (day)"
label variable sb128d_02 "Date measured (day)"
label variable sb128d_03 "Date measured (day)"
label variable sb128d_04 "Date measured (day)"
label variable sb128d_05 "Date measured (day)"
label variable sb128d_06 "Date measured (day)"
label variable sb128d_07 "Date measured (day)"
label variable sb128d_08 "Date measured (day)"
label variable sb128d_09 "Date measured (day)"
label variable sb128d_10 "Date measured (day)"
label variable sb128d_11 "Date measured (day)"
label variable sb128d_12 "Date measured (day)"
label variable sb128d_13 "Date measured (day)"
label variable sb128d_14 "Date measured (day)"
label variable sb128d_15 "Date measured (day)"
label variable sb128d_16 "Date measured (day)"
label variable sb128d_17 "Date measured (day)"
label variable sb128d_18 "Date measured (day)"
label variable sb128d_19 "Date measured (day)"
label variable sb128d_20 "Date measured (day)"
label variable sb128d_21 "Date measured (day)"
label variable sb128d_22 "Date measured (day)"
label variable sb128d_23 "Date measured (day)"
label variable sb128d_24 "Date measured (day)"
label variable sb128d_25 "Date measured (day)"
label variable sb128d_26 "Date measured (day)"
label variable sb128d_27 "Date measured (day)"
label variable sb128d_28 "Date measured (day)"
label variable sb128d_29 "Date measured (day)"
label variable sb128d_30 "Date measured (day)"
label variable sb128d_31 "Date measured (day)"
label variable sb128d_32 "Date measured (day)"
label variable sb128d_33 "Date measured (day)"
label variable sb128m_01 "Date measured (month)"
label variable sb128m_02 "Date measured (month)"
label variable sb128m_03 "Date measured (month)"
label variable sb128m_04 "Date measured (month)"
label variable sb128m_05 "Date measured (month)"
label variable sb128m_06 "Date measured (month)"
label variable sb128m_07 "Date measured (month)"
label variable sb128m_08 "Date measured (month)"
label variable sb128m_09 "Date measured (month)"
label variable sb128m_10 "Date measured (month)"
label variable sb128m_11 "Date measured (month)"
label variable sb128m_12 "Date measured (month)"
label variable sb128m_13 "Date measured (month)"
label variable sb128m_14 "Date measured (month)"
label variable sb128m_15 "Date measured (month)"
label variable sb128m_16 "Date measured (month)"
label variable sb128m_17 "Date measured (month)"
label variable sb128m_18 "Date measured (month)"
label variable sb128m_19 "Date measured (month)"
label variable sb128m_20 "Date measured (month)"
label variable sb128m_21 "Date measured (month)"
label variable sb128m_22 "Date measured (month)"
label variable sb128m_23 "Date measured (month)"
label variable sb128m_24 "Date measured (month)"
label variable sb128m_25 "Date measured (month)"
label variable sb128m_26 "Date measured (month)"
label variable sb128m_27 "Date measured (month)"
label variable sb128m_28 "Date measured (month)"
label variable sb128m_29 "Date measured (month)"
label variable sb128m_30 "Date measured (month)"
label variable sb128m_31 "Date measured (month)"
label variable sb128m_32 "Date measured (month)"
label variable sb128m_33 "Date measured (month)"
label variable sb128y_01 "Date measured (year)"
label variable sb128y_02 "Date measured (year)"
label variable sb128y_03 "Date measured (year)"
label variable sb128y_04 "Date measured (year)"
label variable sb128y_05 "Date measured (year)"
label variable sb128y_06 "Date measured (year)"
label variable sb128y_07 "Date measured (year)"
label variable sb128y_08 "Date measured (year)"
label variable sb128y_09 "Date measured (year)"
label variable sb128y_10 "Date measured (year)"
label variable sb128y_11 "Date measured (year)"
label variable sb128y_12 "Date measured (year)"
label variable sb128y_13 "Date measured (year)"
label variable sb128y_14 "Date measured (year)"
label variable sb128y_15 "Date measured (year)"
label variable sb128y_16 "Date measured (year)"
label variable sb128y_17 "Date measured (year)"
label variable sb128y_18 "Date measured (year)"
label variable sb128y_19 "Date measured (year)"
label variable sb128y_20 "Date measured (year)"
label variable sb128y_21 "Date measured (year)"
label variable sb128y_22 "Date measured (year)"
label variable sb128y_23 "Date measured (year)"
label variable sb128y_24 "Date measured (year)"
label variable sb128y_25 "Date measured (year)"
label variable sb128y_26 "Date measured (year)"
label variable sb128y_27 "Date measured (year)"
label variable sb128y_28 "Date measured (year)"
label variable sb128y_29 "Date measured (year)"
label variable sb128y_30 "Date measured (year)"
label variable sb128y_31 "Date measured (year)"
label variable sb128y_32 "Date measured (year)"
label variable sb128y_33 "Date measured (year)"

#delimit ;
label define HV003   
     0 "Incomplete household"
;
label define HV015   
     1 "Completed"
     2 "No Household member/no competent member at home"
     3 "Entire Household absent for extended period of time"
     4 "Postponed"
     5 "Refused"
     6 "Dwelling vacant or address not a dwelling"
     7 "Dwelling destroyed"
     8 "Dwelling not found"
     9 "Other"
;
label define HV017   
     9 "Missing"
;
label define HV020   
     0 "All woman sample"
     1 "Ever married sample"
;
label define HV022   
     1 "Agadez: Urban"
     2 "Agadez: Rural"
     3 "Diffa: Urban"
     4 "Diffa: Rural"
     5 "Dosso: Urban"
     6 "Dosso: Rural"
     7 "Maradi: Urban"
     8 "Maradi: Rural"
     9 "Tahoua: Urban"
    10 "Tahoua: Rural"
    11 "Tillaberi: Urban"
    12 "Tillaberi: Rural"
    13 "Zinder: Urban"
    14 "Zinder: Rural"
    15 "Niamey: Urban"
    16 "Niamey: Rural"
;
label define HV023   
     1 "Agadez: Urban"
     2 "Agadez: Rural"
     3 "Diffa: Urban"
     4 "Diffa: Rural"
     5 "Dosso: Urban"
     6 "Dosso: Rural"
     7 "Maradi: Urban"
     8 "Maradi: Rural"
     9 "Tahoua: Urban"
    10 "Tahoua: Rural"
    11 "Tillaberi: Urban"
    12 "Tillaberi: Rural"
    13 "Zinder: Urban"
    14 "Zinder: Rural"
    15 "Niamey: Urban"
    16 "Niamey: Rural"
;
label define HV024   
     1 "Agadez"
     2 "Diffa"
     3 "Dosso"
     4 "Maradi"
     5 "Tahoua"
     6 "Tillaberi"
     7 "Zinder"
     8 "Niamey"
;
label define HV025   
     1 "Urban"
     2 "Rural"
;
label define HV026   
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
;
label define HV027   
     0 "Not selected"
     1 "Men's survey"
     2 "Husband's survey"
;
label define HV040   
  9999 "Missing"
;
label define HV042   
     0 "Not selected"
     1 "Selected"
;
label define HV045A  
     1 "French"
     2 "Haoussa"
     3 "Zerma"
;
label define HV045B  
     1 "French"
     2 "Haoussa"
     3 "Zerma"
     4 "Tamasheq"
     5 "Fulfulde"
     6 "Kanouri / Toubou"
     7 "Arabic"
     8 "Gourmantchema"
    96 "Other"
;
label define HV045C  
     1 "French"
     2 "Haoussa"
     3 "Zerma"
     4 "Tamasheq"
     5 "Fulfulde"
     6 "Kanouri / Toubou"
     7 "Arabic"
     8 "Gourmantchema"
    96 "Other"
;
label define HV046   
     0 "No"
     1 "Yes"
;
label define HV801   
  9999 "Missing"
;
label define HV802   
  9999 "Missing"
;
label define HV803   
    95 "95+"
    96 "2+ visits"
    97 "Inconsistent"
;
label define HV804   
     9 "Missing"
;
label define HV201   
    10 "PIPED WATER"
    11 "Piped into dwelling"
    12 "Piped to yard/plot"
    13 "Piped to neighbor"
    14 "Public tap/standpipe"
    20 "TUBE WELL WATER"
    21 "Tube well or borehole"
    30 "DUG WELL (OPEN/PROTECTED)"
    31 "Protected well"
    32 "Unprotected well"
    40 "SURFACE FROM SPRING"
    41 "Protected spring"
    42 "Unprotected spring"
    43 "River/dam/lake/ponds/stream/canal/irrigation channel"
    51 "Rainwater"
    61 "Tanker truck"
    62 "Cart with small tank"
    71 "Bottled water"
    72 "Sachet water"
    96 "Other"
;
label define HV202   
    10 "PIPED WATER"
    11 "Piped into dwelling"
    12 "Piped to yard/plot"
    13 "Piped to neighbor"
    14 "Public tap/standpipe"
    20 "TUBE WELL WATER"
    21 "Tube well or borehole"
    30 "DUG WELL (OPEN/PROTECTED)"
    31 "Protected well"
    32 "Unprotected well"
    40 "SURFACE FROM SPRING"
    41 "Protected spring"
    42 "Unprotected spring"
    43 "River/dam/lake/ponds/stream/canal/irrigation channel"
    51 "Rainwater"
    61 "Tanker truck"
    62 "Cart with small tank"
    71 "Bottled water"
    96 "Other"
;
label define HV201A  
     0 "No, not interrupted for a full day"
     1 "Yes, interrupted for a full day or more"
     8 "Don't know"
;
label define HV204   
   996 "On premises"
   998 "Don't know"
;
label define HV205   
    10 "FLUSH TOILET"
    11 "Flush to piped sewer system"
    12 "Flush to septic tank"
    13 "Flush to pit latrine"
    14 "Flush to somewhere else"
    15 "Flush, don't know where"
    20 "PIT TOILET LATRINE"
    21 "Ventilated Improved Pit latrine (VIP)"
    22 "Pit latrine with slab"
    23 "Pit latrine without slab/open pit"
    30 "NO FACILITY"
    31 "No facility/bush/field"
    41 "Composting toilet"
    42 "Bucket toilet"
    43 "Hanging toilet/latrine"
    96 "Other"
;
label define HV206   
     0 "No"
     1 "Yes"
;
label define HV207   
     0 "No"
     1 "Yes"
;
label define HV208   
     0 "No"
     1 "Yes"
;
label define HV209   
     0 "No"
     1 "Yes"
;
label define HV210   
     0 "No"
     1 "Yes"
;
label define HV211   
     0 "No"
     1 "Yes"
;
label define HV212   
     0 "No"
     1 "Yes"
;
label define HV213   
    10 "NATURAL"
    11 "Earth/sand"
    12 "Dung"
    20 "RUDIMENTARY"
    21 "Wood planks"
    22 "Palm/Bamboo"
    30 "FINISHED"
    31 "Parquet / Polished wood"
    32 "Vynil or asphalt strips"
    33 "Ceramic tiles"
    34 "Cement"
    35 "Carpet"
    96 "Other"
;
label define HV214   
    10 "NATURAL"
    11 "No walls"
    12 "Bamboo/Cane/palm/leaf"
    13 "Dirt"
    20 "RUDIMENTARY"
    21 "Bamboo with mud"
    22 "Stone with mud"
    23 "Uncovered adobe"
    24 "Plywood"
    25 "Cardboard"
    26 "Reused wood"
    30 "FINISHED"
    31 "Cement"
    32 "Stone with lime/cement"
    33 "Bricks"
    34 "Cement blocks"
    35 "Covered adobe"
    36 "Wood planks/shingles"
    96 "Other"
;
label define HV215   
    10 "NATURAL"
    11 "No roof"
    12 "Thatch/palms/leafs"
    13 "Sod"
    20 "RUDIMENTARY"
    21 "Rustic mat"
    22 "Palm/bamboo"
    23 "Wood planks"
    24 "Cardboard"
    30 "FINISHED"
    31 "Sheet Metal"
    32 "Wood"
    33 "Zinc/Cement fiber"
    34 "Tiles/slate"
    35 "Cement"
    36 "Shingles"
    96 "Other"
;
label define HV216   
    99 "Missing"
;
label define HV217   
     0 "No adults"
     1 "One adult"
     2 "Two adults, opposite sex"
     3 "Two adults, same sex"
     4 "Three+ related adults"
     5 "Unrelated adults"
;
label define HV219   
     1 "Male"
     2 "Female"
;
label define HV220   
    97 "97+"
    98 "Don't know"
;
label define HV221   
     0 "No"
     1 "Yes"
;
label define HV225   
     0 "No"
     1 "Yes"
;
label define HV226   
     1 "Electricity"
     2 "Solar energy"
     3 "Liquefied propane gas (LPG)/cooking gas"
     4 "Piped natural gas"
     5 "Biogas"
     6 "Alcohol/ethanol"
     7 "Gasoline/diesel"
     8 "Paraffin/petroleum"
     9 "Coal/lignite"
    10 "Charcoal"
    11 "Wood"
    12 "Straw/shrubs/grass"
    13 "Agricultural crop"
    14 "Animal dung/waste"
    15 "Processed biomass (pellets) or woodchips"
    16 "Garbage/plastic"
    17 "Sawdust"
    95 "No food cooked in house"
    96 "Other"
;
label define HV227   
     0 "No"
     1 "Yes"
;
label define HV228   
     0 "No"
     1 "All children"
     2 "Some children"
     3 "No net in household"
;
label define HV235   
     1 "In own dwelling"
     2 "In own yard/plot"
     3 "Elsewhere"
;
label define HV238   
    95 "10 or more households"
    98 "Don't know"
;
label define HV238A  
     1 "In own dwelling"
     2 "In own yard/plot"
     3 "Elsewhere"
;
label define HV243A  
     0 "No"
     1 "Yes"
;
label define HV243B  
     0 "No"
     1 "Yes"
;
label define HV243C  
     0 "No"
     1 "Yes"
;
label define HV243D  
     0 "No"
     1 "Yes"
;
label define HV243E  
     0 "No"
     1 "Yes"
;
label define HV244   
     0 "No"
     1 "Yes"
;
label define HV245   
   950 "95 or more"
   998 "Unknown"
;
label define HV246   
     0 "No"
     1 "Yes"
;
label define HV246A  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246B  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246C  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246D  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246E  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246F  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246G  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246H  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246I  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246J  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246K  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV247   
     0 "No"
     1 "Yes"
;
label define HV270   
     1 "Poorest"
     2 "Poorer"
     3 "Middle"
     4 "Richer"
     5 "Richest"
;
label define HV270A  
     1 "Poorest"
     2 "Poorer"
     3 "Middle"
     4 "Richer"
     5 "Richest"
;
label define HML1    
    98 "Don't know"
;
label define HML2    
    99 "Missing"
;
label define HV222   
     1 "Electric stove"
     2 "Solar cooker"
     3 "Liquefied propane gas (LPG)/cooking gas stove"
     4 "Piped natural gas stove"
     5 "Biogas stove"
     6 "Liquid fuel stove"
     7 "Manufactured solid fuel stove"
     8 "Traditional solid fuel stove"
     9 "Three stone stove/open fire"
    95 "No food cooked in household"
    96 "Other"
;
label define HV223   
     1 "Alcohol/ethanol"
     2 "Gasoline/diesel"
     3 "Paraffin/Petroleum"
     4 "Coal/lignite"
     5 "Charcoal"
     6 "Wood"
     7 "Straw/shrubs/grass"
     8 "Agricultural crop"
     9 "Animal dung/waste"
    10 "Processed biomass (pellets) or woodchips"
    11 "Garbage/plastic"
    12 "Sawdust"
    96 "Other"
;
label define SH116G  
     0 "No"
     1 "Yes"
;
label define SH116H  
     0 "No"
     1 "Yes"
;
label define SH116I  
     0 "No"
     1 "Yes"
;
label define SH116J  
     0 "No"
     1 "Yes"
;
label define SH116K  
     0 "No"
     1 "Yes"
;
label define SH116L  
     0 "No"
     1 "Yes"
;
label define SH116M  
     0 "No"
     1 "Yes"
;
label define SH116N  
     0 "No"
     1 "Yes"
;
label define SH116O  
     0 "No"
     1 "Yes"
;
label define SH116P  
     0 "No"
     1 "Yes"
;
label define SH117H  
     1 "Yes"
     0 "No"
;
label define SH117I  
     1 "Yes"
     0 "No"
;
label define SH117J  
     1 "Yes"
     0 "No"
;
label define SH117K  
     1 "Yes"
     0 "No"
;
label define SH117L  
     1 "Yes"
     0 "No"
;
label define SH117M  
     1 "Yes"
     0 "No"
;
label define SH117N  
     1 "Yes"
     0 "No"
;
label define SH117O  
     1 "Yes"
     0 "No"
;
label define SH119   
     1 "Yes"
     0 "No"
;
label define HV101   
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster/wife's/husband's child"
    12 "Not related"
    98 "Don't know"
;
label define HV102   
     0 "No"
     1 "Yes"
;
label define HV103   
     0 "No"
     1 "Yes"
;
label define HV104   
     1 "Male"
     2 "Female"
;
label define HV105   
    95 "95+"
    98 "Don't know"
;
label define HV117   
     0 "Not eligible"
     1 "Eligible"
;
label define HV120   
     0 "Not eligible"
     1 "Eligible"
;
label define HC16    
    97 "Inconsistent"
    98 "Don't know"
;
label define HC27    
     1 "Male"
     2 "Female"
;
label define HC30    
    97 "Inconsistent"
    98 "Don't know"
;
label define HC31    
  9997 "Inconsistent"
  9998 "Don't know"
;
label define HC33    
     0 "Month, year and day"
     1 "Month and year - information complete"
     2 "Month and age - year imputed"
     3 "Year and age - month imputed"
     5 "Year - age/month imputed"
     6 "Age - year/month imputed"
     7 "Month - age/year imputed"
     8 "None - all imputed"
;
label define HC51    
     0 "Not in household"
;
label define HC52    
     1 "Granted"
     2 "Refused"
     3 "Not present/other"
;
label define HC53    
   994 "Not present"
   995 "Refused"
   996 "Other"
;
label define HC55    
     0 "Measured"
     3 "Not present/other"
     4 "Refused"
     6 "Other"
;
label define HC56    
   997 "Inconsistent"
;
label define HC57    
     1 "Severe"
     2 "Moderate"
     3 "Mild"
     4 "Not anemic"
;
label define HC58    
     0 "No"
     1 "Yes"
;
label define HC60    
   993 "Mother not de facto"
   994 "Incomplete woman's interview"
   995 "Not in household"
;
label define HC61    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
;
label define HC62    
    98 "Don't know"
;
label define HC63    
   999 "Missing"
;
label define HC64    
    99 "Missing"
;
label define HC68    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
;
label define HML3    
     0 "Not seen"
     1 "Yes, seen"
;
label define HML4    
    96 "More than 3 years ago"
    98 "Don't know"
;
label define HML5    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HML6    
     0 "Not pretreated"
     1 "Pretreated, permanent treatment"
     2 "Pretreated, requiring future treatment"
     3 "Not pretreated, came with kit and treated at home"
     4 "Pretreated, treatment type not known"
     6 "Other"
     8 "Don't know"
;
label define HML7    
    10 "Long-lasting insecticide treated nets (LLIN)"
    11 "Dawaplus 2.0"
    12 "Duranet"
    13 "Interceptor G2"
    14 "Olyset net"
    15 "Permanet 2.0"
    16 "Royal sentry"
    17 "Safenet"
    18 "Life net"
    19 "Yorkool ln"
    26 "Other/don't know the brand (LLIN)"
    96 "Other brand (Not LLIN)"
    98 "DK brand"
;
label define HML8    
     0 "No"
     1 "Yes"
     2 "Permanent/LLIN net"
     8 "Not sure"
;
label define HML9    
    95 "25+ months ago"
    96 "More than 3 years ago"
    98 "Don't know"
;
label define HML10   
     0 "No, don't know"
     1 "Yes"
;
label define HML11   
     5 "5+"
;
label define HML21   
     0 "No"
     1 "Yes"
     8 "Not sure (DK)"
;
label define HMLA    
     0 "No one"
;
label define HMLB    
    99 "Missing"
;
label define HMLC    
    99 "Missing"
;
label define HML22   
     0 "No"
     1 "Yes, campaign LLIN"
     2 "Yes, antenatal care"
     3 "Yes, immunization visit"
;
label define HML23   
    10 "Government health facility"
    11 "Government health facility"
    20 "Private health facility"
    21 "Private health facility"
    30 "Other sources"
    31 "Pharmacy"
    32 "Shop/market"
    33 "CHW"
    34 "Religious institution"
    35 "School"
    36 "NGO"
    96 "Other"
    98 "Don't know"
;
label define SH130   
     1 "Very hot"
     2 "Don't like the shape of the mosquito net"
     3 "Don't like the color of the mosquito net"
     4 "Don't like the size of the mosquito net"
     5 "Don't like the smell of the mosquito net"
     6 "Unable to suspend her"
     7 "Slept outside"
     8 "Regular user didn't sleep here last night"
     9 "No mosquitoes / no malaria"
    10 "Additional mosquito net / kept for later"
    96 "Other"
;
label define HML12   
     0 "Did not sleep under a net"
     1 "Only treated (ITN) nets"
     2 "Both treated (ITN) and untreated nets"
     3 "Only untreated nets"
;
label define HML13   
     0 "Did not sleep under net"
;
label define HML16   
    97 "97+"
    98 "Don't know"
;
label define HML17   
     0 "No data from Individual file"
     1 "Month and year - information complete"
     2 "Month and age - year imputed"
     3 "Year and age - month imputed"
     4 "Year and age - year ignored"
     5 "Year - age/month imputed"
     6 "Age - year/month imputed"
     7 "Month - age/year imputed"
     8 "None - all imputed"
;
label define HML18   
     0 "Not pregnant, don't know"
     1 "Pregnant"
;
label define HML19   
     0 "No"
     1 "Yes"
;
label define HML20   
     0 "No"
     1 "Yes"
;
label define HML30   
     0 "Not in household"
;
label define HML31   
     1 "Granted"
     2 "Parent/other responsible refused"
     3 "Respondent refused"
     4 "Adult/parent not present"
     5 "Minor not present"
;
label define HML32   
     0 "Negative"
     1 "Positive"
     6 "Test undetermined"
     7 "Sample not found in lab database"
;
label define HML32A  
     0 "No"
     1 "Yes"
;
label define HML32B  
     0 "No"
     1 "Yes"
;
label define HML32C  
     0 "No"
     1 "Yes"
;
label define HML32D  
     0 "No"
     1 "Yes"
;
label define HML32E  
     0 "No"
     1 "Yes"
;
label define HML32F  
     0 "No"
     1 "Yes"
;
label define HML32G  
     0 "No"
     1 "Yes"
;
label define HML33   
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
;
label define HML35   
     0 "Negative"
     1 "Positive"
     6 "Other"
;
label define SB114   
     0 "Negative"
     1 "Positive"
     4 "Not present"
     5 "Refused"
     6 "Other"
;
label define SB115A  
     0 "No"
     1 "Yes"
;
label define SB115B  
     0 "No"
     1 "Yes"
;
label define SB115C  
     0 "No"
     1 "Yes"
;
label define SB115D  
     0 "No"
     1 "Yes"
;
label define SB115E  
     0 "No"
     1 "Yes"
;
label define SB115F  
     0 "No"
     1 "Yes"
;
label define SB115G  
     0 "No"
     1 "Yes"
;
label define SB115H  
     0 "No"
     1 "Yes"
;
label define SB117   
     1 "Below 8.0 G/DL, severe anemia"
     2 "8.0 G/DL or above"
     6 "Other"
;
label define SB119   
     0 "No"
     1 "Yes"
;
label define SB122   
     1 "Medicine accepted"
     2 "Medicine refused"
     6 "Other"
;
label define SB126   
     1 "Below 8.0 G/DL, severe anemia"
     2 "8.0 G/DL or above"
     6 "Other"
;
label define SB128Y  
  2021 "2021"
;

#delimit cr
label values hv003    HV003   
label values hv015    HV015   
label values hv020    HV020   
label values hv022    HV022   
label values hv023    HV023   
label values hv024    HV024   
label values hv025    HV025   
label values hv026    HV026   
label values hv027    HV027   
label values hv042    HV042   
label values hv045a   HV045A  
label values hv045b   HV045B  
label values hv045c   HV045C  
label values hv046    HV046   
label values hv803    HV803   
label values hv201    HV201   
label values hv202    HV202   
label values hv201a   HV201A  
label values hv204    HV204   
label values hv205    HV205   
label values hv206    HV206   
label values hv207    HV207   
label values hv208    HV208   
label values hv209    HV209   
label values hv210    HV210   
label values hv211    HV211   
label values hv212    HV212   
label values hv213    HV213   
label values hv214    HV214   
label values hv215    HV215   
label values hv217    HV217   
label values hv219    HV219   
label values hv220    HV220   
label values hv221    HV221   
label values hv225    HV225   
label values hv226    HV226   
label values hv227    HV227   
label values hv228    HV228   
label values hv235    HV235   
label values hv238    HV238   
label values hv238a   HV238A  
label values hv243a   HV243A  
label values hv243b   HV243B  
label values hv243c   HV243C  
label values hv243d   HV243D  
label values hv243e   HV243E  
label values hv244    HV244   
label values hv245    HV245   
label values hv246    HV246   
label values hv246a   HV246A  
label values hv246b   HV246B  
label values hv246c   HV246C  
label values hv246d   HV246D  
label values hv246e   HV246E  
label values hv246f   HV246F  
label values hv246g   HV246G  
label values hv246h   HV246H  
label values hv246i   HV246I  
label values hv246j   HV246J  
label values hv246k   HV246K  
label values hv247    HV247   
label values hv270    HV270   
label values hv270a   HV270A  
label values hml1     HML1    
label values hv222    HV222   
label values hv223    HV223   
label values sh116g   SH116G  
label values sh116h   SH116H  
label values sh116i   SH116I  
label values sh116j   SH116J  
label values sh116k   SH116K  
label values sh116l   SH116L  
label values sh116m   SH116M  
label values sh116n   SH116N  
label values sh116o   SH116O  
label values sh116p   SH116P  
label values sh117h   SH117H  
label values sh117i   SH117I  
label values sh117j   SH117J  
label values sh117k   SH117K  
label values sh117l   SH117L  
label values sh117m   SH117M  
label values sh117n   SH117N  
label values sh117o   SH117O  
label values sh119    SH119   
label values hv101_01 HV101   
label values hv101_02 HV101   
label values hv101_03 HV101   
label values hv101_04 HV101   
label values hv101_05 HV101   
label values hv101_06 HV101   
label values hv101_07 HV101   
label values hv101_08 HV101   
label values hv101_09 HV101   
label values hv101_10 HV101   
label values hv101_11 HV101   
label values hv101_12 HV101   
label values hv101_13 HV101   
label values hv101_14 HV101   
label values hv101_15 HV101   
label values hv101_16 HV101   
label values hv101_17 HV101   
label values hv101_18 HV101   
label values hv101_19 HV101   
label values hv101_20 HV101   
label values hv101_21 HV101   
label values hv101_22 HV101   
label values hv101_23 HV101   
label values hv101_24 HV101   
label values hv101_25 HV101   
label values hv101_26 HV101   
label values hv101_27 HV101   
label values hv101_28 HV101   
label values hv101_29 HV101   
label values hv101_30 HV101   
label values hv101_31 HV101   
label values hv101_32 HV101   
label values hv101_33 HV101   
label values hv102_01 HV102   
label values hv102_02 HV102   
label values hv102_03 HV102   
label values hv102_04 HV102   
label values hv102_05 HV102   
label values hv102_06 HV102   
label values hv102_07 HV102   
label values hv102_08 HV102   
label values hv102_09 HV102   
label values hv102_10 HV102   
label values hv102_11 HV102   
label values hv102_12 HV102   
label values hv102_13 HV102   
label values hv102_14 HV102   
label values hv102_15 HV102   
label values hv102_16 HV102   
label values hv102_17 HV102   
label values hv102_18 HV102   
label values hv102_19 HV102   
label values hv102_20 HV102   
label values hv102_21 HV102   
label values hv102_22 HV102   
label values hv102_23 HV102   
label values hv102_24 HV102   
label values hv102_25 HV102   
label values hv102_26 HV102   
label values hv102_27 HV102   
label values hv102_28 HV102   
label values hv102_29 HV102   
label values hv102_30 HV102   
label values hv102_31 HV102   
label values hv102_32 HV102   
label values hv102_33 HV102   
label values hv103_01 HV103   
label values hv103_02 HV103   
label values hv103_03 HV103   
label values hv103_04 HV103   
label values hv103_05 HV103   
label values hv103_06 HV103   
label values hv103_07 HV103   
label values hv103_08 HV103   
label values hv103_09 HV103   
label values hv103_10 HV103   
label values hv103_11 HV103   
label values hv103_12 HV103   
label values hv103_13 HV103   
label values hv103_14 HV103   
label values hv103_15 HV103   
label values hv103_16 HV103   
label values hv103_17 HV103   
label values hv103_18 HV103   
label values hv103_19 HV103   
label values hv103_20 HV103   
label values hv103_21 HV103   
label values hv103_22 HV103   
label values hv103_23 HV103   
label values hv103_24 HV103   
label values hv103_25 HV103   
label values hv103_26 HV103   
label values hv103_27 HV103   
label values hv103_28 HV103   
label values hv103_29 HV103   
label values hv103_30 HV103   
label values hv103_31 HV103   
label values hv103_32 HV103   
label values hv103_33 HV103   
label values hv104_01 HV104   
label values hv104_02 HV104   
label values hv104_03 HV104   
label values hv104_04 HV104   
label values hv104_05 HV104   
label values hv104_06 HV104   
label values hv104_07 HV104   
label values hv104_08 HV104   
label values hv104_09 HV104   
label values hv104_10 HV104   
label values hv104_11 HV104   
label values hv104_12 HV104   
label values hv104_13 HV104   
label values hv104_14 HV104   
label values hv104_15 HV104   
label values hv104_16 HV104   
label values hv104_17 HV104   
label values hv104_18 HV104   
label values hv104_19 HV104   
label values hv104_20 HV104   
label values hv104_21 HV104   
label values hv104_22 HV104   
label values hv104_23 HV104   
label values hv104_24 HV104   
label values hv104_25 HV104   
label values hv104_26 HV104   
label values hv104_27 HV104   
label values hv104_28 HV104   
label values hv104_29 HV104   
label values hv104_30 HV104   
label values hv104_31 HV104   
label values hv104_32 HV104   
label values hv104_33 HV104   
label values hv105_01 HV105   
label values hv105_02 HV105   
label values hv105_03 HV105   
label values hv105_04 HV105   
label values hv105_05 HV105   
label values hv105_06 HV105   
label values hv105_07 HV105   
label values hv105_08 HV105   
label values hv105_09 HV105   
label values hv105_10 HV105   
label values hv105_11 HV105   
label values hv105_12 HV105   
label values hv105_13 HV105   
label values hv105_14 HV105   
label values hv105_15 HV105   
label values hv105_16 HV105   
label values hv105_17 HV105   
label values hv105_18 HV105   
label values hv105_19 HV105   
label values hv105_20 HV105   
label values hv105_21 HV105   
label values hv105_22 HV105   
label values hv105_23 HV105   
label values hv105_24 HV105   
label values hv105_25 HV105   
label values hv105_26 HV105   
label values hv105_27 HV105   
label values hv105_28 HV105   
label values hv105_29 HV105   
label values hv105_30 HV105   
label values hv105_31 HV105   
label values hv105_32 HV105   
label values hv105_33 HV105   
label values hv117_01 HV117   
label values hv117_02 HV117   
label values hv117_03 HV117   
label values hv117_04 HV117   
label values hv117_05 HV117   
label values hv117_06 HV117   
label values hv117_07 HV117   
label values hv117_08 HV117   
label values hv117_09 HV117   
label values hv117_10 HV117   
label values hv117_11 HV117   
label values hv117_12 HV117   
label values hv117_13 HV117   
label values hv117_14 HV117   
label values hv117_15 HV117   
label values hv117_16 HV117   
label values hv117_17 HV117   
label values hv117_18 HV117   
label values hv117_19 HV117   
label values hv117_20 HV117   
label values hv117_21 HV117   
label values hv117_22 HV117   
label values hv117_23 HV117   
label values hv117_24 HV117   
label values hv117_25 HV117   
label values hv117_26 HV117   
label values hv117_27 HV117   
label values hv117_28 HV117   
label values hv117_29 HV117   
label values hv117_30 HV117   
label values hv117_31 HV117   
label values hv117_32 HV117   
label values hv117_33 HV117   
label values hv120_01 HV120   
label values hv120_02 HV120   
label values hv120_03 HV120   
label values hv120_04 HV120   
label values hv120_05 HV120   
label values hv120_06 HV120   
label values hv120_07 HV120   
label values hv120_08 HV120   
label values hv120_09 HV120   
label values hv120_10 HV120   
label values hv120_11 HV120   
label values hv120_12 HV120   
label values hv120_13 HV120   
label values hv120_14 HV120   
label values hv120_15 HV120   
label values hv120_16 HV120   
label values hv120_17 HV120   
label values hv120_18 HV120   
label values hv120_19 HV120   
label values hv120_20 HV120   
label values hv120_21 HV120   
label values hv120_22 HV120   
label values hv120_23 HV120   
label values hv120_24 HV120   
label values hv120_25 HV120   
label values hv120_26 HV120   
label values hv120_27 HV120   
label values hv120_28 HV120   
label values hv120_29 HV120   
label values hv120_30 HV120   
label values hv120_31 HV120   
label values hv120_32 HV120   
label values hv120_33 HV120   
label values hc16_1   HC16    
label values hc16_2   HC16    
label values hc16_3   HC16    
label values hc16_4   HC16    
label values hc16_5   HC16    
label values hc16_6   HC16    
label values hc16_7   HC16    
label values hc27_1   HC27    
label values hc27_2   HC27    
label values hc27_3   HC27    
label values hc27_4   HC27    
label values hc27_5   HC27    
label values hc27_6   HC27    
label values hc27_7   HC27    
label values hc30_1   HC30    
label values hc30_2   HC30    
label values hc30_3   HC30    
label values hc30_4   HC30    
label values hc30_5   HC30    
label values hc30_6   HC30    
label values hc30_7   HC30    
label values hc31_1   HC31    
label values hc31_2   HC31    
label values hc31_3   HC31    
label values hc31_4   HC31    
label values hc31_5   HC31    
label values hc31_6   HC31    
label values hc31_7   HC31    
label values hc33_1   HC33    
label values hc33_2   HC33    
label values hc33_3   HC33    
label values hc33_4   HC33    
label values hc33_5   HC33    
label values hc33_6   HC33    
label values hc33_7   HC33    
label values hc51_1   HC51    
label values hc51_2   HC51    
label values hc51_3   HC51    
label values hc51_4   HC51    
label values hc51_5   HC51    
label values hc51_6   HC51    
label values hc51_7   HC51    
label values hc52_1   HC52    
label values hc52_2   HC52    
label values hc52_3   HC52    
label values hc52_4   HC52    
label values hc52_5   HC52    
label values hc52_6   HC52    
label values hc52_7   HC52    
label values hc53_1   HC53    
label values hc53_2   HC53    
label values hc53_3   HC53    
label values hc53_4   HC53    
label values hc53_5   HC53    
label values hc53_6   HC53    
label values hc53_7   HC53    
label values hc55_1   HC55    
label values hc55_2   HC55    
label values hc55_3   HC55    
label values hc55_4   HC55    
label values hc55_5   HC55    
label values hc55_6   HC55    
label values hc55_7   HC55    
label values hc56_1   HC56    
label values hc56_2   HC56    
label values hc56_3   HC56    
label values hc56_4   HC56    
label values hc56_5   HC56    
label values hc56_6   HC56    
label values hc56_7   HC56    
label values hc57_1   HC57    
label values hc57_2   HC57    
label values hc57_3   HC57    
label values hc57_4   HC57    
label values hc57_5   HC57    
label values hc57_6   HC57    
label values hc57_7   HC57    
label values hc58_1   HC58    
label values hc58_2   HC58    
label values hc58_3   HC58    
label values hc58_4   HC58    
label values hc58_5   HC58    
label values hc58_6   HC58    
label values hc58_7   HC58    
label values hc60_1   HC60    
label values hc60_2   HC60    
label values hc60_3   HC60    
label values hc60_4   HC60    
label values hc60_5   HC60    
label values hc60_6   HC60    
label values hc60_7   HC60    
label values hc61_1   HC61    
label values hc61_2   HC61    
label values hc61_3   HC61    
label values hc61_4   HC61    
label values hc61_5   HC61    
label values hc61_6   HC61    
label values hc61_7   HC61    
label values hc62_1   HC62    
label values hc62_2   HC62    
label values hc62_3   HC62    
label values hc62_4   HC62    
label values hc62_5   HC62    
label values hc62_6   HC62    
label values hc62_7   HC62    
label values hc68_1   HC68    
label values hc68_2   HC68    
label values hc68_3   HC68    
label values hc68_4   HC68    
label values hc68_5   HC68    
label values hc68_6   HC68    
label values hc68_7   HC68    
label values hml3_1   HML3    
label values hml3_2   HML3    
label values hml3_3   HML3    
label values hml3_4   HML3    
label values hml3_5   HML3    
label values hml3_6   HML3    
label values hml3_7   HML3    
label values hml4_1   HML4    
label values hml4_2   HML4    
label values hml4_3   HML4    
label values hml4_4   HML4    
label values hml4_5   HML4    
label values hml4_6   HML4    
label values hml4_7   HML4    
label values hml5_1   HML5    
label values hml5_2   HML5    
label values hml5_3   HML5    
label values hml5_4   HML5    
label values hml5_5   HML5    
label values hml5_6   HML5    
label values hml5_7   HML5    
label values hml6_1   HML6    
label values hml6_2   HML6    
label values hml6_3   HML6    
label values hml6_4   HML6    
label values hml6_5   HML6    
label values hml6_6   HML6    
label values hml6_7   HML6    
label values hml7_1   HML7    
label values hml7_2   HML7    
label values hml7_3   HML7    
label values hml7_4   HML7    
label values hml7_5   HML7    
label values hml7_6   HML7    
label values hml7_7   HML7    
label values hml8_1   HML8    
label values hml8_2   HML8    
label values hml8_3   HML8    
label values hml8_4   HML8    
label values hml8_5   HML8    
label values hml8_6   HML8    
label values hml8_7   HML8    
label values hml9_1   HML9    
label values hml9_2   HML9    
label values hml9_3   HML9    
label values hml9_4   HML9    
label values hml9_5   HML9    
label values hml9_6   HML9    
label values hml9_7   HML9    
label values hml10_1  HML10   
label values hml10_2  HML10   
label values hml10_3  HML10   
label values hml10_4  HML10   
label values hml10_5  HML10   
label values hml10_6  HML10   
label values hml10_7  HML10   
label values hml11_1  HML11   
label values hml11_2  HML11   
label values hml11_3  HML11   
label values hml11_4  HML11   
label values hml11_5  HML11   
label values hml11_6  HML11   
label values hml11_7  HML11   
label values hml21_1  HML21   
label values hml21_2  HML21   
label values hml21_3  HML21   
label values hml21_4  HML21   
label values hml21_5  HML21   
label values hml21_6  HML21   
label values hml21_7  HML21   
label values hmla_1   HMLA    
label values hmla_2   HMLA    
label values hmla_3   HMLA    
label values hmla_4   HMLA    
label values hmla_5   HMLA    
label values hmla_6   HMLA    
label values hmla_7   HMLA    
label values hml22_1  HML22   
label values hml22_2  HML22   
label values hml22_3  HML22   
label values hml22_4  HML22   
label values hml22_5  HML22   
label values hml22_6  HML22   
label values hml22_7  HML22   
label values hml23_1  HML23   
label values hml23_2  HML23   
label values hml23_3  HML23   
label values hml23_4  HML23   
label values hml23_5  HML23   
label values hml23_6  HML23   
label values hml23_7  HML23   
label values sh130_1  SH130   
label values sh130_2  SH130   
label values sh130_3  SH130   
label values sh130_4  SH130   
label values sh130_5  SH130   
label values sh130_6  SH130   
label values sh130_7  SH130   
label values hml12_01 HML12   
label values hml12_02 HML12   
label values hml12_03 HML12   
label values hml12_04 HML12   
label values hml12_05 HML12   
label values hml12_06 HML12   
label values hml12_07 HML12   
label values hml12_08 HML12   
label values hml12_09 HML12   
label values hml12_10 HML12   
label values hml12_11 HML12   
label values hml12_12 HML12   
label values hml12_13 HML12   
label values hml12_14 HML12   
label values hml12_15 HML12   
label values hml12_16 HML12   
label values hml12_17 HML12   
label values hml12_18 HML12   
label values hml12_19 HML12   
label values hml12_20 HML12   
label values hml12_21 HML12   
label values hml12_22 HML12   
label values hml12_23 HML12   
label values hml12_24 HML12   
label values hml12_25 HML12   
label values hml12_26 HML12   
label values hml12_27 HML12   
label values hml12_28 HML12   
label values hml12_29 HML12   
label values hml12_30 HML12   
label values hml12_31 HML12   
label values hml12_32 HML12   
label values hml12_33 HML12   
label values hml13_01 HML13   
label values hml13_02 HML13   
label values hml13_03 HML13   
label values hml13_04 HML13   
label values hml13_05 HML13   
label values hml13_06 HML13   
label values hml13_07 HML13   
label values hml13_08 HML13   
label values hml13_09 HML13   
label values hml13_10 HML13   
label values hml13_11 HML13   
label values hml13_12 HML13   
label values hml13_13 HML13   
label values hml13_14 HML13   
label values hml13_15 HML13   
label values hml13_16 HML13   
label values hml13_17 HML13   
label values hml13_18 HML13   
label values hml13_19 HML13   
label values hml13_20 HML13   
label values hml13_21 HML13   
label values hml13_22 HML13   
label values hml13_23 HML13   
label values hml13_24 HML13   
label values hml13_25 HML13   
label values hml13_26 HML13   
label values hml13_27 HML13   
label values hml13_28 HML13   
label values hml13_29 HML13   
label values hml13_30 HML13   
label values hml13_31 HML13   
label values hml13_32 HML13   
label values hml13_33 HML13   
label values hml16_01 HML16   
label values hml16_02 HML16   
label values hml16_03 HML16   
label values hml16_04 HML16   
label values hml16_05 HML16   
label values hml16_06 HML16   
label values hml16_07 HML16   
label values hml16_08 HML16   
label values hml16_09 HML16   
label values hml16_10 HML16   
label values hml16_11 HML16   
label values hml16_12 HML16   
label values hml16_13 HML16   
label values hml16_14 HML16   
label values hml16_15 HML16   
label values hml16_16 HML16   
label values hml16_17 HML16   
label values hml16_18 HML16   
label values hml16_19 HML16   
label values hml16_20 HML16   
label values hml16_21 HML16   
label values hml16_22 HML16   
label values hml16_23 HML16   
label values hml16_24 HML16   
label values hml16_25 HML16   
label values hml16_26 HML16   
label values hml16_27 HML16   
label values hml16_28 HML16   
label values hml16_29 HML16   
label values hml16_30 HML16   
label values hml16_31 HML16   
label values hml16_32 HML16   
label values hml16_33 HML16   
label values hml17_01 HML17   
label values hml17_02 HML17   
label values hml17_03 HML17   
label values hml17_04 HML17   
label values hml17_05 HML17   
label values hml17_06 HML17   
label values hml17_07 HML17   
label values hml17_08 HML17   
label values hml17_09 HML17   
label values hml17_10 HML17   
label values hml17_11 HML17   
label values hml17_12 HML17   
label values hml17_13 HML17   
label values hml17_14 HML17   
label values hml17_15 HML17   
label values hml17_16 HML17   
label values hml17_17 HML17   
label values hml17_18 HML17   
label values hml17_19 HML17   
label values hml17_20 HML17   
label values hml17_21 HML17   
label values hml17_22 HML17   
label values hml17_23 HML17   
label values hml17_24 HML17   
label values hml17_25 HML17   
label values hml17_26 HML17   
label values hml17_27 HML17   
label values hml17_28 HML17   
label values hml17_29 HML17   
label values hml17_30 HML17   
label values hml17_31 HML17   
label values hml17_32 HML17   
label values hml17_33 HML17   
label values hml18_01 HML18   
label values hml18_02 HML18   
label values hml18_03 HML18   
label values hml18_04 HML18   
label values hml18_05 HML18   
label values hml18_06 HML18   
label values hml18_07 HML18   
label values hml18_08 HML18   
label values hml18_09 HML18   
label values hml18_10 HML18   
label values hml18_11 HML18   
label values hml18_12 HML18   
label values hml18_13 HML18   
label values hml18_14 HML18   
label values hml18_15 HML18   
label values hml18_16 HML18   
label values hml18_17 HML18   
label values hml18_18 HML18   
label values hml18_19 HML18   
label values hml18_20 HML18   
label values hml18_21 HML18   
label values hml18_22 HML18   
label values hml18_23 HML18   
label values hml18_24 HML18   
label values hml18_25 HML18   
label values hml18_26 HML18   
label values hml18_27 HML18   
label values hml18_28 HML18   
label values hml18_29 HML18   
label values hml18_30 HML18   
label values hml18_31 HML18   
label values hml18_32 HML18   
label values hml18_33 HML18   
label values hml19_01 HML19   
label values hml19_02 HML19   
label values hml19_03 HML19   
label values hml19_04 HML19   
label values hml19_05 HML19   
label values hml19_06 HML19   
label values hml19_07 HML19   
label values hml19_08 HML19   
label values hml19_09 HML19   
label values hml19_10 HML19   
label values hml19_11 HML19   
label values hml19_12 HML19   
label values hml19_13 HML19   
label values hml19_14 HML19   
label values hml19_15 HML19   
label values hml19_16 HML19   
label values hml19_17 HML19   
label values hml19_18 HML19   
label values hml19_19 HML19   
label values hml19_20 HML19   
label values hml19_21 HML19   
label values hml19_22 HML19   
label values hml19_23 HML19   
label values hml19_24 HML19   
label values hml19_25 HML19   
label values hml19_26 HML19   
label values hml19_27 HML19   
label values hml19_28 HML19   
label values hml19_29 HML19   
label values hml19_30 HML19   
label values hml19_31 HML19   
label values hml19_32 HML19   
label values hml19_33 HML19   
label values hml20_01 HML20   
label values hml20_02 HML20   
label values hml20_03 HML20   
label values hml20_04 HML20   
label values hml20_05 HML20   
label values hml20_06 HML20   
label values hml20_07 HML20   
label values hml20_08 HML20   
label values hml20_09 HML20   
label values hml20_10 HML20   
label values hml20_11 HML20   
label values hml20_12 HML20   
label values hml20_13 HML20   
label values hml20_14 HML20   
label values hml20_15 HML20   
label values hml20_16 HML20   
label values hml20_17 HML20   
label values hml20_18 HML20   
label values hml20_19 HML20   
label values hml20_20 HML20   
label values hml20_21 HML20   
label values hml20_22 HML20   
label values hml20_23 HML20   
label values hml20_24 HML20   
label values hml20_25 HML20   
label values hml20_26 HML20   
label values hml20_27 HML20   
label values hml20_28 HML20   
label values hml20_29 HML20   
label values hml20_30 HML20   
label values hml20_31 HML20   
label values hml20_32 HML20   
label values hml20_33 HML20   
label values hml30_01 HML30   
label values hml30_02 HML30   
label values hml30_03 HML30   
label values hml30_04 HML30   
label values hml30_05 HML30   
label values hml30_06 HML30   
label values hml30_07 HML30   
label values hml30_08 HML30   
label values hml30_09 HML30   
label values hml30_10 HML30   
label values hml30_11 HML30   
label values hml30_12 HML30   
label values hml30_13 HML30   
label values hml30_14 HML30   
label values hml30_15 HML30   
label values hml30_16 HML30   
label values hml30_17 HML30   
label values hml30_18 HML30   
label values hml30_19 HML30   
label values hml30_20 HML30   
label values hml30_21 HML30   
label values hml30_22 HML30   
label values hml30_23 HML30   
label values hml30_24 HML30   
label values hml30_25 HML30   
label values hml30_26 HML30   
label values hml30_27 HML30   
label values hml30_28 HML30   
label values hml30_29 HML30   
label values hml30_30 HML30   
label values hml30_31 HML30   
label values hml30_32 HML30   
label values hml30_33 HML30   
label values hml31_01 HML31   
label values hml31_02 HML31   
label values hml31_03 HML31   
label values hml31_04 HML31   
label values hml31_05 HML31   
label values hml31_06 HML31   
label values hml31_07 HML31   
label values hml31_08 HML31   
label values hml31_09 HML31   
label values hml31_10 HML31   
label values hml31_11 HML31   
label values hml31_12 HML31   
label values hml31_13 HML31   
label values hml31_14 HML31   
label values hml31_15 HML31   
label values hml31_16 HML31   
label values hml31_17 HML31   
label values hml31_18 HML31   
label values hml31_19 HML31   
label values hml31_20 HML31   
label values hml31_21 HML31   
label values hml31_22 HML31   
label values hml31_23 HML31   
label values hml31_24 HML31   
label values hml31_25 HML31   
label values hml31_26 HML31   
label values hml31_27 HML31   
label values hml31_28 HML31   
label values hml31_29 HML31   
label values hml31_30 HML31   
label values hml31_31 HML31   
label values hml31_32 HML31   
label values hml31_33 HML31   
label values hml32_01 HML32   
label values hml32_02 HML32   
label values hml32_03 HML32   
label values hml32_04 HML32   
label values hml32_05 HML32   
label values hml32_06 HML32   
label values hml32_07 HML32   
label values hml32_08 HML32   
label values hml32_09 HML32   
label values hml32_10 HML32   
label values hml32_11 HML32   
label values hml32_12 HML32   
label values hml32_13 HML32   
label values hml32_14 HML32   
label values hml32_15 HML32   
label values hml32_16 HML32   
label values hml32_17 HML32   
label values hml32_18 HML32   
label values hml32_19 HML32   
label values hml32_20 HML32   
label values hml32_21 HML32   
label values hml32_22 HML32   
label values hml32_23 HML32   
label values hml32_24 HML32   
label values hml32_25 HML32   
label values hml32_26 HML32   
label values hml32_27 HML32   
label values hml32_28 HML32   
label values hml32_29 HML32   
label values hml32_30 HML32   
label values hml32_31 HML32   
label values hml32_32 HML32   
label values hml32_33 HML32   
label values hml32a_01 HML32A  
label values hml32a_02 HML32A  
label values hml32a_03 HML32A  
label values hml32a_04 HML32A  
label values hml32a_05 HML32A  
label values hml32a_06 HML32A  
label values hml32a_07 HML32A  
label values hml32a_08 HML32A  
label values hml32a_09 HML32A  
label values hml32a_10 HML32A  
label values hml32a_11 HML32A  
label values hml32a_12 HML32A  
label values hml32a_13 HML32A  
label values hml32a_14 HML32A  
label values hml32a_15 HML32A  
label values hml32a_16 HML32A  
label values hml32a_17 HML32A  
label values hml32a_18 HML32A  
label values hml32a_19 HML32A  
label values hml32a_20 HML32A  
label values hml32a_21 HML32A  
label values hml32a_22 HML32A  
label values hml32a_23 HML32A  
label values hml32a_24 HML32A  
label values hml32a_25 HML32A  
label values hml32a_26 HML32A  
label values hml32a_27 HML32A  
label values hml32a_28 HML32A  
label values hml32a_29 HML32A  
label values hml32a_30 HML32A  
label values hml32a_31 HML32A  
label values hml32a_32 HML32A  
label values hml32a_33 HML32A  
label values hml32b_01 HML32B  
label values hml32b_02 HML32B  
label values hml32b_03 HML32B  
label values hml32b_04 HML32B  
label values hml32b_05 HML32B  
label values hml32b_06 HML32B  
label values hml32b_07 HML32B  
label values hml32b_08 HML32B  
label values hml32b_09 HML32B  
label values hml32b_10 HML32B  
label values hml32b_11 HML32B  
label values hml32b_12 HML32B  
label values hml32b_13 HML32B  
label values hml32b_14 HML32B  
label values hml32b_15 HML32B  
label values hml32b_16 HML32B  
label values hml32b_17 HML32B  
label values hml32b_18 HML32B  
label values hml32b_19 HML32B  
label values hml32b_20 HML32B  
label values hml32b_21 HML32B  
label values hml32b_22 HML32B  
label values hml32b_23 HML32B  
label values hml32b_24 HML32B  
label values hml32b_25 HML32B  
label values hml32b_26 HML32B  
label values hml32b_27 HML32B  
label values hml32b_28 HML32B  
label values hml32b_29 HML32B  
label values hml32b_30 HML32B  
label values hml32b_31 HML32B  
label values hml32b_32 HML32B  
label values hml32b_33 HML32B  
label values hml32c_01 HML32C  
label values hml32c_02 HML32C  
label values hml32c_03 HML32C  
label values hml32c_04 HML32C  
label values hml32c_05 HML32C  
label values hml32c_06 HML32C  
label values hml32c_07 HML32C  
label values hml32c_08 HML32C  
label values hml32c_09 HML32C  
label values hml32c_10 HML32C  
label values hml32c_11 HML32C  
label values hml32c_12 HML32C  
label values hml32c_13 HML32C  
label values hml32c_14 HML32C  
label values hml32c_15 HML32C  
label values hml32c_16 HML32C  
label values hml32c_17 HML32C  
label values hml32c_18 HML32C  
label values hml32c_19 HML32C  
label values hml32c_20 HML32C  
label values hml32c_21 HML32C  
label values hml32c_22 HML32C  
label values hml32c_23 HML32C  
label values hml32c_24 HML32C  
label values hml32c_25 HML32C  
label values hml32c_26 HML32C  
label values hml32c_27 HML32C  
label values hml32c_28 HML32C  
label values hml32c_29 HML32C  
label values hml32c_30 HML32C  
label values hml32c_31 HML32C  
label values hml32c_32 HML32C  
label values hml32c_33 HML32C  
label values hml32d_01 HML32D  
label values hml32d_02 HML32D  
label values hml32d_03 HML32D  
label values hml32d_04 HML32D  
label values hml32d_05 HML32D  
label values hml32d_06 HML32D  
label values hml32d_07 HML32D  
label values hml32d_08 HML32D  
label values hml32d_09 HML32D  
label values hml32d_10 HML32D  
label values hml32d_11 HML32D  
label values hml32d_12 HML32D  
label values hml32d_13 HML32D  
label values hml32d_14 HML32D  
label values hml32d_15 HML32D  
label values hml32d_16 HML32D  
label values hml32d_17 HML32D  
label values hml32d_18 HML32D  
label values hml32d_19 HML32D  
label values hml32d_20 HML32D  
label values hml32d_21 HML32D  
label values hml32d_22 HML32D  
label values hml32d_23 HML32D  
label values hml32d_24 HML32D  
label values hml32d_25 HML32D  
label values hml32d_26 HML32D  
label values hml32d_27 HML32D  
label values hml32d_28 HML32D  
label values hml32d_29 HML32D  
label values hml32d_30 HML32D  
label values hml32d_31 HML32D  
label values hml32d_32 HML32D  
label values hml32d_33 HML32D  
label values hml32e_01 HML32E  
label values hml32e_02 HML32E  
label values hml32e_03 HML32E  
label values hml32e_04 HML32E  
label values hml32e_05 HML32E  
label values hml32e_06 HML32E  
label values hml32e_07 HML32E  
label values hml32e_08 HML32E  
label values hml32e_09 HML32E  
label values hml32e_10 HML32E  
label values hml32e_11 HML32E  
label values hml32e_12 HML32E  
label values hml32e_13 HML32E  
label values hml32e_14 HML32E  
label values hml32e_15 HML32E  
label values hml32e_16 HML32E  
label values hml32e_17 HML32E  
label values hml32e_18 HML32E  
label values hml32e_19 HML32E  
label values hml32e_20 HML32E  
label values hml32e_21 HML32E  
label values hml32e_22 HML32E  
label values hml32e_23 HML32E  
label values hml32e_24 HML32E  
label values hml32e_25 HML32E  
label values hml32e_26 HML32E  
label values hml32e_27 HML32E  
label values hml32e_28 HML32E  
label values hml32e_29 HML32E  
label values hml32e_30 HML32E  
label values hml32e_31 HML32E  
label values hml32e_32 HML32E  
label values hml32e_33 HML32E  
label values hml32f_01 HML32F  
label values hml32f_02 HML32F  
label values hml32f_03 HML32F  
label values hml32f_04 HML32F  
label values hml32f_05 HML32F  
label values hml32f_06 HML32F  
label values hml32f_07 HML32F  
label values hml32f_08 HML32F  
label values hml32f_09 HML32F  
label values hml32f_10 HML32F  
label values hml32f_11 HML32F  
label values hml32f_12 HML32F  
label values hml32f_13 HML32F  
label values hml32f_14 HML32F  
label values hml32f_15 HML32F  
label values hml32f_16 HML32F  
label values hml32f_17 HML32F  
label values hml32f_18 HML32F  
label values hml32f_19 HML32F  
label values hml32f_20 HML32F  
label values hml32f_21 HML32F  
label values hml32f_22 HML32F  
label values hml32f_23 HML32F  
label values hml32f_24 HML32F  
label values hml32f_25 HML32F  
label values hml32f_26 HML32F  
label values hml32f_27 HML32F  
label values hml32f_28 HML32F  
label values hml32f_29 HML32F  
label values hml32f_30 HML32F  
label values hml32f_31 HML32F  
label values hml32f_32 HML32F  
label values hml32f_33 HML32F  
label values hml32g_01 HML32G  
label values hml32g_02 HML32G  
label values hml32g_03 HML32G  
label values hml32g_04 HML32G  
label values hml32g_05 HML32G  
label values hml32g_06 HML32G  
label values hml32g_07 HML32G  
label values hml32g_08 HML32G  
label values hml32g_09 HML32G  
label values hml32g_10 HML32G  
label values hml32g_11 HML32G  
label values hml32g_12 HML32G  
label values hml32g_13 HML32G  
label values hml32g_14 HML32G  
label values hml32g_15 HML32G  
label values hml32g_16 HML32G  
label values hml32g_17 HML32G  
label values hml32g_18 HML32G  
label values hml32g_19 HML32G  
label values hml32g_20 HML32G  
label values hml32g_21 HML32G  
label values hml32g_22 HML32G  
label values hml32g_23 HML32G  
label values hml32g_24 HML32G  
label values hml32g_25 HML32G  
label values hml32g_26 HML32G  
label values hml32g_27 HML32G  
label values hml32g_28 HML32G  
label values hml32g_29 HML32G  
label values hml32g_30 HML32G  
label values hml32g_31 HML32G  
label values hml32g_32 HML32G  
label values hml32g_33 HML32G  
label values hml33_01 HML33   
label values hml33_02 HML33   
label values hml33_03 HML33   
label values hml33_04 HML33   
label values hml33_05 HML33   
label values hml33_06 HML33   
label values hml33_07 HML33   
label values hml33_08 HML33   
label values hml33_09 HML33   
label values hml33_10 HML33   
label values hml33_11 HML33   
label values hml33_12 HML33   
label values hml33_13 HML33   
label values hml33_14 HML33   
label values hml33_15 HML33   
label values hml33_16 HML33   
label values hml33_17 HML33   
label values hml33_18 HML33   
label values hml33_19 HML33   
label values hml33_20 HML33   
label values hml33_21 HML33   
label values hml33_22 HML33   
label values hml33_23 HML33   
label values hml33_24 HML33   
label values hml33_25 HML33   
label values hml33_26 HML33   
label values hml33_27 HML33   
label values hml33_28 HML33   
label values hml33_29 HML33   
label values hml33_30 HML33   
label values hml33_31 HML33   
label values hml33_32 HML33   
label values hml33_33 HML33   
label values hml35_01 HML35   
label values hml35_02 HML35   
label values hml35_03 HML35   
label values hml35_04 HML35   
label values hml35_05 HML35   
label values hml35_06 HML35   
label values hml35_07 HML35   
label values hml35_08 HML35   
label values hml35_09 HML35   
label values hml35_10 HML35   
label values hml35_11 HML35   
label values hml35_12 HML35   
label values hml35_13 HML35   
label values hml35_14 HML35   
label values hml35_15 HML35   
label values hml35_16 HML35   
label values hml35_17 HML35   
label values hml35_18 HML35   
label values hml35_19 HML35   
label values hml35_20 HML35   
label values hml35_21 HML35   
label values hml35_22 HML35   
label values hml35_23 HML35   
label values hml35_24 HML35   
label values hml35_25 HML35   
label values hml35_26 HML35   
label values hml35_27 HML35   
label values hml35_28 HML35   
label values hml35_29 HML35   
label values hml35_30 HML35   
label values hml35_31 HML35   
label values hml35_32 HML35   
label values hml35_33 HML35   
label values sb114_01 SB114   
label values sb114_02 SB114   
label values sb114_03 SB114   
label values sb114_04 SB114   
label values sb114_05 SB114   
label values sb114_06 SB114   
label values sb114_07 SB114   
label values sb114_08 SB114   
label values sb114_09 SB114   
label values sb114_10 SB114   
label values sb114_11 SB114   
label values sb114_12 SB114   
label values sb114_13 SB114   
label values sb114_14 SB114   
label values sb114_15 SB114   
label values sb114_16 SB114   
label values sb114_17 SB114   
label values sb114_18 SB114   
label values sb114_19 SB114   
label values sb114_20 SB114   
label values sb114_21 SB114   
label values sb114_22 SB114   
label values sb114_23 SB114   
label values sb114_24 SB114   
label values sb114_25 SB114   
label values sb114_26 SB114   
label values sb114_27 SB114   
label values sb114_28 SB114   
label values sb114_29 SB114   
label values sb114_30 SB114   
label values sb114_31 SB114   
label values sb114_32 SB114   
label values sb114_33 SB114   
label values sb115a_01 SB115A  
label values sb115a_02 SB115A  
label values sb115a_03 SB115A  
label values sb115a_04 SB115A  
label values sb115a_05 SB115A  
label values sb115a_06 SB115A  
label values sb115a_07 SB115A  
label values sb115a_08 SB115A  
label values sb115a_09 SB115A  
label values sb115a_10 SB115A  
label values sb115a_11 SB115A  
label values sb115a_12 SB115A  
label values sb115a_13 SB115A  
label values sb115a_14 SB115A  
label values sb115a_15 SB115A  
label values sb115a_16 SB115A  
label values sb115a_17 SB115A  
label values sb115a_18 SB115A  
label values sb115a_19 SB115A  
label values sb115a_20 SB115A  
label values sb115a_21 SB115A  
label values sb115a_22 SB115A  
label values sb115a_23 SB115A  
label values sb115a_24 SB115A  
label values sb115a_25 SB115A  
label values sb115a_26 SB115A  
label values sb115a_27 SB115A  
label values sb115a_28 SB115A  
label values sb115a_29 SB115A  
label values sb115a_30 SB115A  
label values sb115a_31 SB115A  
label values sb115a_32 SB115A  
label values sb115a_33 SB115A  
label values sb115b_01 SB115B  
label values sb115b_02 SB115B  
label values sb115b_03 SB115B  
label values sb115b_04 SB115B  
label values sb115b_05 SB115B  
label values sb115b_06 SB115B  
label values sb115b_07 SB115B  
label values sb115b_08 SB115B  
label values sb115b_09 SB115B  
label values sb115b_10 SB115B  
label values sb115b_11 SB115B  
label values sb115b_12 SB115B  
label values sb115b_13 SB115B  
label values sb115b_14 SB115B  
label values sb115b_15 SB115B  
label values sb115b_16 SB115B  
label values sb115b_17 SB115B  
label values sb115b_18 SB115B  
label values sb115b_19 SB115B  
label values sb115b_20 SB115B  
label values sb115b_21 SB115B  
label values sb115b_22 SB115B  
label values sb115b_23 SB115B  
label values sb115b_24 SB115B  
label values sb115b_25 SB115B  
label values sb115b_26 SB115B  
label values sb115b_27 SB115B  
label values sb115b_28 SB115B  
label values sb115b_29 SB115B  
label values sb115b_30 SB115B  
label values sb115b_31 SB115B  
label values sb115b_32 SB115B  
label values sb115b_33 SB115B  
label values sb115c_01 SB115C  
label values sb115c_02 SB115C  
label values sb115c_03 SB115C  
label values sb115c_04 SB115C  
label values sb115c_05 SB115C  
label values sb115c_06 SB115C  
label values sb115c_07 SB115C  
label values sb115c_08 SB115C  
label values sb115c_09 SB115C  
label values sb115c_10 SB115C  
label values sb115c_11 SB115C  
label values sb115c_12 SB115C  
label values sb115c_13 SB115C  
label values sb115c_14 SB115C  
label values sb115c_15 SB115C  
label values sb115c_16 SB115C  
label values sb115c_17 SB115C  
label values sb115c_18 SB115C  
label values sb115c_19 SB115C  
label values sb115c_20 SB115C  
label values sb115c_21 SB115C  
label values sb115c_22 SB115C  
label values sb115c_23 SB115C  
label values sb115c_24 SB115C  
label values sb115c_25 SB115C  
label values sb115c_26 SB115C  
label values sb115c_27 SB115C  
label values sb115c_28 SB115C  
label values sb115c_29 SB115C  
label values sb115c_30 SB115C  
label values sb115c_31 SB115C  
label values sb115c_32 SB115C  
label values sb115c_33 SB115C  
label values sb115d_01 SB115D  
label values sb115d_02 SB115D  
label values sb115d_03 SB115D  
label values sb115d_04 SB115D  
label values sb115d_05 SB115D  
label values sb115d_06 SB115D  
label values sb115d_07 SB115D  
label values sb115d_08 SB115D  
label values sb115d_09 SB115D  
label values sb115d_10 SB115D  
label values sb115d_11 SB115D  
label values sb115d_12 SB115D  
label values sb115d_13 SB115D  
label values sb115d_14 SB115D  
label values sb115d_15 SB115D  
label values sb115d_16 SB115D  
label values sb115d_17 SB115D  
label values sb115d_18 SB115D  
label values sb115d_19 SB115D  
label values sb115d_20 SB115D  
label values sb115d_21 SB115D  
label values sb115d_22 SB115D  
label values sb115d_23 SB115D  
label values sb115d_24 SB115D  
label values sb115d_25 SB115D  
label values sb115d_26 SB115D  
label values sb115d_27 SB115D  
label values sb115d_28 SB115D  
label values sb115d_29 SB115D  
label values sb115d_30 SB115D  
label values sb115d_31 SB115D  
label values sb115d_32 SB115D  
label values sb115d_33 SB115D  
label values sb115e_01 SB115E  
label values sb115e_02 SB115E  
label values sb115e_03 SB115E  
label values sb115e_04 SB115E  
label values sb115e_05 SB115E  
label values sb115e_06 SB115E  
label values sb115e_07 SB115E  
label values sb115e_08 SB115E  
label values sb115e_09 SB115E  
label values sb115e_10 SB115E  
label values sb115e_11 SB115E  
label values sb115e_12 SB115E  
label values sb115e_13 SB115E  
label values sb115e_14 SB115E  
label values sb115e_15 SB115E  
label values sb115e_16 SB115E  
label values sb115e_17 SB115E  
label values sb115e_18 SB115E  
label values sb115e_19 SB115E  
label values sb115e_20 SB115E  
label values sb115e_21 SB115E  
label values sb115e_22 SB115E  
label values sb115e_23 SB115E  
label values sb115e_24 SB115E  
label values sb115e_25 SB115E  
label values sb115e_26 SB115E  
label values sb115e_27 SB115E  
label values sb115e_28 SB115E  
label values sb115e_29 SB115E  
label values sb115e_30 SB115E  
label values sb115e_31 SB115E  
label values sb115e_32 SB115E  
label values sb115e_33 SB115E  
label values sb115f_01 SB115F  
label values sb115f_02 SB115F  
label values sb115f_03 SB115F  
label values sb115f_04 SB115F  
label values sb115f_05 SB115F  
label values sb115f_06 SB115F  
label values sb115f_07 SB115F  
label values sb115f_08 SB115F  
label values sb115f_09 SB115F  
label values sb115f_10 SB115F  
label values sb115f_11 SB115F  
label values sb115f_12 SB115F  
label values sb115f_13 SB115F  
label values sb115f_14 SB115F  
label values sb115f_15 SB115F  
label values sb115f_16 SB115F  
label values sb115f_17 SB115F  
label values sb115f_18 SB115F  
label values sb115f_19 SB115F  
label values sb115f_20 SB115F  
label values sb115f_21 SB115F  
label values sb115f_22 SB115F  
label values sb115f_23 SB115F  
label values sb115f_24 SB115F  
label values sb115f_25 SB115F  
label values sb115f_26 SB115F  
label values sb115f_27 SB115F  
label values sb115f_28 SB115F  
label values sb115f_29 SB115F  
label values sb115f_30 SB115F  
label values sb115f_31 SB115F  
label values sb115f_32 SB115F  
label values sb115f_33 SB115F  
label values sb115g_01 SB115G  
label values sb115g_02 SB115G  
label values sb115g_03 SB115G  
label values sb115g_04 SB115G  
label values sb115g_05 SB115G  
label values sb115g_06 SB115G  
label values sb115g_07 SB115G  
label values sb115g_08 SB115G  
label values sb115g_09 SB115G  
label values sb115g_10 SB115G  
label values sb115g_11 SB115G  
label values sb115g_12 SB115G  
label values sb115g_13 SB115G  
label values sb115g_14 SB115G  
label values sb115g_15 SB115G  
label values sb115g_16 SB115G  
label values sb115g_17 SB115G  
label values sb115g_18 SB115G  
label values sb115g_19 SB115G  
label values sb115g_20 SB115G  
label values sb115g_21 SB115G  
label values sb115g_22 SB115G  
label values sb115g_23 SB115G  
label values sb115g_24 SB115G  
label values sb115g_25 SB115G  
label values sb115g_26 SB115G  
label values sb115g_27 SB115G  
label values sb115g_28 SB115G  
label values sb115g_29 SB115G  
label values sb115g_30 SB115G  
label values sb115g_31 SB115G  
label values sb115g_32 SB115G  
label values sb115g_33 SB115G  
label values sb115h_01 SB115H  
label values sb115h_02 SB115H  
label values sb115h_03 SB115H  
label values sb115h_04 SB115H  
label values sb115h_05 SB115H  
label values sb115h_06 SB115H  
label values sb115h_07 SB115H  
label values sb115h_08 SB115H  
label values sb115h_09 SB115H  
label values sb115h_10 SB115H  
label values sb115h_11 SB115H  
label values sb115h_12 SB115H  
label values sb115h_13 SB115H  
label values sb115h_14 SB115H  
label values sb115h_15 SB115H  
label values sb115h_16 SB115H  
label values sb115h_17 SB115H  
label values sb115h_18 SB115H  
label values sb115h_19 SB115H  
label values sb115h_20 SB115H  
label values sb115h_21 SB115H  
label values sb115h_22 SB115H  
label values sb115h_23 SB115H  
label values sb115h_24 SB115H  
label values sb115h_25 SB115H  
label values sb115h_26 SB115H  
label values sb115h_27 SB115H  
label values sb115h_28 SB115H  
label values sb115h_29 SB115H  
label values sb115h_30 SB115H  
label values sb115h_31 SB115H  
label values sb115h_32 SB115H  
label values sb115h_33 SB115H  
label values sb117_01 SB117   
label values sb117_02 SB117   
label values sb117_03 SB117   
label values sb117_04 SB117   
label values sb117_05 SB117   
label values sb117_06 SB117   
label values sb117_07 SB117   
label values sb117_08 SB117   
label values sb117_09 SB117   
label values sb117_10 SB117   
label values sb117_11 SB117   
label values sb117_12 SB117   
label values sb117_13 SB117   
label values sb117_14 SB117   
label values sb117_15 SB117   
label values sb117_16 SB117   
label values sb117_17 SB117   
label values sb117_18 SB117   
label values sb117_19 SB117   
label values sb117_20 SB117   
label values sb117_21 SB117   
label values sb117_22 SB117   
label values sb117_23 SB117   
label values sb117_24 SB117   
label values sb117_25 SB117   
label values sb117_26 SB117   
label values sb117_27 SB117   
label values sb117_28 SB117   
label values sb117_29 SB117   
label values sb117_30 SB117   
label values sb117_31 SB117   
label values sb117_32 SB117   
label values sb117_33 SB117   
label values sb119_01 SB119   
label values sb119_02 SB119   
label values sb119_03 SB119   
label values sb119_04 SB119   
label values sb119_05 SB119   
label values sb119_06 SB119   
label values sb119_07 SB119   
label values sb119_08 SB119   
label values sb119_09 SB119   
label values sb119_10 SB119   
label values sb119_11 SB119   
label values sb119_12 SB119   
label values sb119_13 SB119   
label values sb119_14 SB119   
label values sb119_15 SB119   
label values sb119_16 SB119   
label values sb119_17 SB119   
label values sb119_18 SB119   
label values sb119_19 SB119   
label values sb119_20 SB119   
label values sb119_21 SB119   
label values sb119_22 SB119   
label values sb119_23 SB119   
label values sb119_24 SB119   
label values sb119_25 SB119   
label values sb119_26 SB119   
label values sb119_27 SB119   
label values sb119_28 SB119   
label values sb119_29 SB119   
label values sb119_30 SB119   
label values sb119_31 SB119   
label values sb119_32 SB119   
label values sb119_33 SB119   
label values sb122_01 SB122   
label values sb122_02 SB122   
label values sb122_03 SB122   
label values sb122_04 SB122   
label values sb122_05 SB122   
label values sb122_06 SB122   
label values sb122_07 SB122   
label values sb122_08 SB122   
label values sb122_09 SB122   
label values sb122_10 SB122   
label values sb122_11 SB122   
label values sb122_12 SB122   
label values sb122_13 SB122   
label values sb122_14 SB122   
label values sb122_15 SB122   
label values sb122_16 SB122   
label values sb122_17 SB122   
label values sb122_18 SB122   
label values sb122_19 SB122   
label values sb122_20 SB122   
label values sb122_21 SB122   
label values sb122_22 SB122   
label values sb122_23 SB122   
label values sb122_24 SB122   
label values sb122_25 SB122   
label values sb122_26 SB122   
label values sb122_27 SB122   
label values sb122_28 SB122   
label values sb122_29 SB122   
label values sb122_30 SB122   
label values sb122_31 SB122   
label values sb122_32 SB122   
label values sb122_33 SB122   
label values sb126_01 SB126   
label values sb126_02 SB126   
label values sb126_03 SB126   
label values sb126_04 SB126   
label values sb126_05 SB126   
label values sb126_06 SB126   
label values sb126_07 SB126   
label values sb126_08 SB126   
label values sb126_09 SB126   
label values sb126_10 SB126   
label values sb126_11 SB126   
label values sb126_12 SB126   
label values sb126_13 SB126   
label values sb126_14 SB126   
label values sb126_15 SB126   
label values sb126_16 SB126   
label values sb126_17 SB126   
label values sb126_18 SB126   
label values sb126_19 SB126   
label values sb126_20 SB126   
label values sb126_21 SB126   
label values sb126_22 SB126   
label values sb126_23 SB126   
label values sb126_24 SB126   
label values sb126_25 SB126   
label values sb126_26 SB126   
label values sb126_27 SB126   
label values sb126_28 SB126   
label values sb126_29 SB126   
label values sb126_30 SB126   
label values sb126_31 SB126   
label values sb126_32 SB126   
label values sb126_33 SB126   
label values sb128y_01 SB128Y  
label values sb128y_02 SB128Y  
label values sb128y_03 SB128Y  
label values sb128y_04 SB128Y  
label values sb128y_05 SB128Y  
label values sb128y_06 SB128Y  
label values sb128y_07 SB128Y  
label values sb128y_08 SB128Y  
label values sb128y_09 SB128Y  
label values sb128y_10 SB128Y  
label values sb128y_11 SB128Y  
label values sb128y_12 SB128Y  
label values sb128y_13 SB128Y  
label values sb128y_14 SB128Y  
label values sb128y_15 SB128Y  
label values sb128y_16 SB128Y  
label values sb128y_17 SB128Y  
label values sb128y_18 SB128Y  
label values sb128y_19 SB128Y  
label values sb128y_20 SB128Y  
label values sb128y_21 SB128Y  
label values sb128y_22 SB128Y  
label values sb128y_23 SB128Y  
label values sb128y_24 SB128Y  
label values sb128y_25 SB128Y  
label values sb128y_26 SB128Y  
label values sb128y_27 SB128Y  
label values sb128y_28 SB128Y  
label values sb128y_29 SB128Y  
label values sb128y_30 SB128Y  
label values sb128y_31 SB128Y  
label values sb128y_32 SB128Y  
label values sb128y_33 SB128Y  
